### ISSUE TITLE
Chrome thinks http://openhatch.org/+projects/ is in Galician

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1017]
<b>Comment by <a href='https://openhatch.org/people/jesstess/'>jesstess</a>:</b><dl><dd>When I visit <a href="http://openhatch.org/+projects/,">http://openhatch.org/+projects/,</a> Chrome thinks it is in Galician and offers to translate it 
for me. Since that page is not in Galician, it'd be nice to make whatever change will let Chrome know 
this.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/lauras/'>lauras</a>:</b><dl><dd>Not positive if this works, as the error doesn't come up when run locally.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>We've applied this patch, but I don't think it resolves the issue.

I have no idea how to control this behavior of Chrome, so for now I will mark it
as resolved (as best we can).
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/rafpaf/'>rafpaf</a>:</b><dl><dd>Supposedly this works:
&lt;meta name="google" value="notranslate"&gt;
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Raffi, thanks for finding out the right magic for this.

<a href="http://support.google.com/translate/">http://support.google.com/translate/</a> is an authoritative source claiming that your 
fix should actually do the job.

Laura, are you interested in submitting a new patch with the fix re-done in this 
new way? If so, great -- leave a comment saying so!
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd><a href="http://stackoverflow.com/questions/7228972/disable-chrome-translation-bar-on-my-">http://stackoverflow.com/questions/7228972/disable-chrome-translation-bar-on-my-</a>
website provides examples that indicates this suggested fix isn't actually 
enough.

I think the correct next step is to file a bug, hopefully with a patch, against 
Chrome (AKA Chromium). That's daunting.

We could add the meta tag, and it would solve 80% of the problem -- but if you 
reload the page, the user would still the message about Galician.
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file471/0001-Edited-to-make-project-page-show-up-on-google-Chrome.patch by lauras</b>

Status: <b>chatting</b>
Nosy List: <b>  jesstess, lauras, paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>702</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue702'>view archived page</a>)
Last modified: <b>2012-10-03.20:31:53</b>

**Comment by ehashman** [comment]
Tested and determined it's not, so I'm closing this.
