### ISSUE TITLE
Send our changes to patch.py upstream

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1031]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Right now, we have an outdated version of patch.py in vendor/packages/python-patch/

We should:

* Make a diff between this version and the version we are based on, and create
clear patches for upstream.

* Upgrade our version to upstream's latest.

* See if we fix any bugs upstream hasn't fixed yet.

* If so, we should share our patches. (If not, we should throw away our version.)
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>716</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue716'>view archived page</a>)
Last modified: <b>2012-03-15.00:29:29</b>

**Comment by ehashman** [comment]
There hasn't been a change to patch.py for three years, so I'm going to close this.
