### ISSUE TITLE
Automatically test training missions against live web app

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1047]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>In <a href="issue429">issue429</a> we found that even though the svn mission was passing the internal 
automated tests, a deployment issue meant that the svn mission was not working.

Therefore, we should have automated tests that try the mission via the web 
interface.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>732</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue732'>view archived page</a>)
Last modified: <b>2012-05-14.18:20:54</b>

**Comment by willingc** [comment]
Closing. See #1709.
