### ISSUE TITLE
Sign up (without OpenID) page not looking good

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1073]
<b>Comment by <a href='https://openhatch.org/people/e2jk/'>e2jk</a>:</b><dl><dd>The "Sign up (without OpenID)" page <a href="https://openhatch.org/account/signup/?next=">https://openhatch.org/account/signup/?next=</a> 
looks weird in Chromium 
18.0.1025.168 and Firefox 14.0.1 under Ubuntu 12.04.

As you can see in the attachment, in Chromium the input fields are displayed in 
a casade-like way, with the text to the right of the input field.
In Firefox, the inputs are vertically aligned, but the labels are still on the 
right. I assume the labels should be on the left because (1) it's the usual way 
and (2) the labels end with a semicolon, which would be the case if there was 
something after it.

If you look at the source for the email field:
&lt;p&gt;&lt;label for="id_email"&gt;Email:&lt;/label&gt; &lt;input type="text" name="email" 
id="id_email" /&gt;&lt;/p&gt;
the label comes before the input, and both the label and the input are wrapped 
inside a p tag. All the other fields are built the same way. I suppose there's 
something fishy going on with the CSS, somehow the text, password and file 
inputs and textarea get a "float: left;" property. When deactivating it with 
Firebug (and there are a few of those to deactivate) the fields are displayed 
properly.
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file516/Sign%20up%20without%20OpenID.png by e2jk</b>

Status: <b>unread</b>
Nosy List: <b>  e2jk, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>758</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue758'>view archived page</a>)
Last modified: <b>2012-08-12.15:13:23</b>

**Comment by ehashman** [comment]
I installed Chromium just to test this and have happily discovered it is no longer an issue! Yay!
