### ISSUE TITLE
SVN diff mission error: "The patch affects the wrong file."

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1085]
<b>Comment by <a href='https://openhatch.org/people/Elbinray/'>Elbinray</a>:</b><dl><dd>After submitting what appears to be a valid diff, the SVN "Diffing your changes" 
mission returns an error:

"The patch affects the wrong file."

This bug was brought up on the forums in August, 2011[0], and it either re-
surfaced a short while later or was never fixed. Because of this bug, I am not 
able to continue with the SVN missions.

[0] <a href="http://forum.openhatch.org/discussion/comment/33/">http://forum.openhatch.org/discussion/comment/33/</a>
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  Elbinray, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>770</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue770'>view archived page</a>)
Last modified: <b>2012-09-24.00:51:06</b>

**Comment by njuvan** [comment]
The issue persist, as it seems. I'm getting the same error message: "The patch affects the wrong file." I'm running Linux Mint 17 KDE. I edited the README file, that needed to be corrected, with vim text editor and I tried to submit the diff output via latest Firefox and Chrome browsers but to no success.

**Comment by willingc** [comment]
Closing this issue. Subversion mission will be addressed in #1709
