### ISSUE TITLE
diff-patch mission recommends wget

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1121]
<b>Comment by <a href='https://openhatch.org/people/makearney/'>makearney</a>:</b><dl><dd>FYI, I'm a newbie to this site. I attended Jessica's open source tutorial run 
this weekend, and disocvered a minor issue which I thought I'd report.
I was using windows during the course.
The course recommended git-bash as a cli.
The mission page <a href="https://openhatch.org/missions/diffpatch/single_patch">https://openhatch.org/missions/diffpatch/single_patch</a> (click 
hint level high)
The hint text recommends using "wget" to download the files of interest.
git-bash on windows does not include wget. I just checked the three machines I 
have. None has wget.
git-bash does have curl which provideds the same functionality.
I suggest the hint changed to use curl.
One can also download and install wget, which I did at the tutorial 
except that is time taken away from the tutorial.

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jesstess/'>jesstess</a>:</b><dl><dd>I noticed that this was also an issue on OSX 10.6 - 10.8.

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jwm/'>jwm</a>:</b><dl><dd>
  <a href="https://github.com/openhatch/oh-mainline/pull/94">https://github.com/openhatch/oh-mainline/pull/94</a>

</dl></dd><hr/>

Status: <b>resolved</b>
Nosy List: <b>  jesstess, makearney, mkumm, paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>806</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue806'>view archived page</a>)
Last modified: <b>2013-03-19.00:26:48</b>

**Comment by acanubhav** [comment]
i had the same problem

**Comment by ehashman** [comment]
Hi @acanubhav, I'm not able to reproduce this. Can you please provide more details, i.e. a screenshot and the steps you took when encountering this bug? I'll keep this closed until I hear back from you with more info.
