### ISSUE TITLE
The logged-in user's user page should contain special hints for them

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1188]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>The panels that used to appear at / for logged in users -- 
Projects and Missions (the completed ones) -- we should now find these on the 
user's profile page.

Note that this will require digging through git history to find that content.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/onceuponatimeforever/'>onceuponatimeforever</a>:</b><dl><dd>Suggestion: it can be helpful if there's a screenshot/photoshoppped image of exactly how you 
envision the logged-in user age to look like.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/onceuponatimeforever/'>onceuponatimeforever</a>:</b><dl><dd>PR is here for your review: <a href="https://github.com/openhatch/oh-mainline/pull/127">https://github.com/openhatch/oh-mainline/pull/127</a>
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/brittag/'>brittag</a>:</b><dl><dd>Assigning this to myself because it's currently blocked on me making a little mockup of what it 
should look like.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/brittag/'>brittag</a>:</b><dl><dd>Here is a mockup of what this could look like! I took the "Missions" and "Projects" boxes from the 
old homepage and integrated them into the current profile page structure.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/brittag/'>brittag</a>:</b><dl><dd>For reference, I'm also attaching my screenshot of the old homepage (as seen in my local copy of 
OpenHatch running an old version).
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file564/oh-oldhomepage.png by brittag</b>
<b>File at http://roundup-archive.openhatch.org/bugs/file563/oh-proposedprofile.png by brittag</b>

Status: <b>need-review</b>
Nosy List: <b>  brittag, florapdx, lizzard, onceuponatimeforever, paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>873</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue873'>view archived page</a>)
Last modified: <b>2013-10-28.21:22:46</b>

**Comment by ehashman** [comment]
As the associated PR has been closed, I'm going to close this too.
