### ISSUE TITLE
MySQL-based test suite fails due to problems with fixture loading

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1204]
<b>Comment by <a href='https://openhatch.org/people/jwm/'>jwm</a>:</b><dl><dd>20:33:22&lt; johnmorr&gt; paulproteus: do you have any idea why the travis build would fail (and
 in nonsensical ways) with USE_MYSQL == true?
20:33:38&lt; paulproteus&gt; Sadly yes.
20:33:47 * johnmorr listens to paulproteus.
20:33:54&lt; paulproteus&gt; They mostly relate to some kind of insanity in the inter-dependenci
es between the fixtures and their primary keys.
20:34:07&lt; paulproteus&gt; That's the first one.
20:34:17&lt; paulproteus&gt; You can see some of this with sqlite too, but we skip those tests w
ith sqlite.
20:34:48&lt; paulproteus&gt; Let me go read the log for the rest
20:34:59&lt; johnmorr&gt; <a href="https://travis-ci.org/openhatch/oh-mainline/jobs/12337407">https://travis-ci.org/openhatch/oh-mainline/jobs/12337407</a>
20:35:31&lt; johnmorr&gt; looks like a bunch of twill failures, too
20:35:32&lt; paulproteus&gt; <a href="https://travis-ci.org/openhatch/oh-mainline/jobs/12337093">https://travis-ci.org/openhatch/oh-mainline/jobs/12337093</a> is simply
 because someone needs to 'apt-get install python-mysqldb'
20:35:33&lt; paulproteus&gt; let me read that
20:35:46&lt; paulproteus&gt; The twill failures are usually because the app lacks the data that 
the tests expect, fwiw.
20:35:52&lt; paulproteus&gt; Which are because the fixture loads failed.
20:36:10&lt; paulproteus&gt; iirc we hit this problem with mysql 5.5 and up, but not e.g. 5.0, o
n which we developed ~4y ago
20:36:31&lt; johnmorr&gt; this problem == the fixture loads failing?
20:36:35&lt; paulproteus&gt; Yeah.
20:36:50&lt; paulproteus&gt; Which you should be able to reproduce by doing:
20:36:53&lt; paulproteus&gt; $ export USE_MYSQL=1
20:37:01&lt; paulproteus&gt; $ python manage.py syncdb --noinput
20:37:11&lt; paulproteus&gt; $ python manage.py loaddata just_one_person.json
20:37:26&lt; paulproteus&gt; (where just_one_person.json is the file part of a path of a real file in 
mysite/*/fixtures/* )
20:37:38&lt; paulproteus&gt; (I'm not sure that's a real valid name, but it's a made-up example; I hope 
that's clear enough)
20:37:43&lt; johnmorr&gt; nod paulproteus 
20:38:04&lt; paulproteus&gt; So if you look at the failing tests, and the values of the fixtures list for 
that test, you should probably be able to trigger the insane errors by simply loading them in the 
order they are provided to that test case.
20:38:08&lt; paulproteus&gt; Now... what to do about that.
20:38:33&lt; paulproteus&gt; The lovely Walter iirc at PyCon sprints 2012 (2011??) looked into this for 
a while and came out of it with his head spinning.
20:38:40&lt; paulproteus&gt; Probably we can combine more of the fixtures into one file.
20:38:52&lt; paulproteus&gt; Part of the problem (most of it? all of it?) relates to auto-creating Person 
objects from User objects.
20:38:59&lt; paulproteus&gt; it's all coming back to me...
20:39:06&lt; paulproteus&gt; There's a post-create hook for the User object which makes sure a 
Person object gets made.
20:39:24&lt; paulproteus&gt; But in fixture load time we definitely want not to auto-create the Person 
-- we want to use the Person object that is provided in the JSON!
20:39:28&lt; paulproteus&gt; That's what I recall.
20:39:43&lt; paulproteus&gt; I think that's the whole story. It's relatively bad, but also relatively hairy.
20:39:47&lt; paulproteus&gt; If it could end, that would be fantastic.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jwm/'>jwm</a>:</b><dl><dd>This is a more noticable thing now that <a href="https://github.com/openhatch/oh-mainline/pull/146">https://github.com/openhatch/oh-mainline/pull/146</a> has 
been merged.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/mandarg/'>mandarg</a>:</b><dl><dd>More IRC snippets between me and paulproteus about this:

[8:21pm] mandarg: well, it was about the MYSQL=true test failures
[8:21pm] paulproteus: Mm, do ask!
[8:21pm] paulproteus: Those are interesting and complex.
[8:21pm] paulproteus: The fix, however, is simple I believe.
[8:21pm] paulproteus: Which is to stop using tc.go() etc.
[8:22pm] mandarg: is the problem that data is not getting loaded into the database when the tests are 
executed, but there is no way of making sure the data is in before they start?
[8:22pm] paulproteus: So...
[8:22pm] paulproteus: The data is getting loaded into the database.
[8:22pm] paulproteus: However, it's loaded in a transaction and not visible from other transactions.
[8:22pm] paulproteus: The extent to which is "in" the database is questionable, you might see.
[8:22pm] paulproteus: This is a feature of the Django test runner; doing it this way, as you saw, makes 
for huge performance advantages.
[8:23pm] paulproteus: The built-in Django "test client" seems to work properly with this, by making 
sure to use the same MySQL connection as the one that did the insertion.
[8:23pm] paulproteus: All is well.
[8:23pm] mandarg: ah
[8:23pm] paulproteus: But the Twill-based test suite somehow is not using the same MySQL 
connection, I believe.
[8:23pm] paulproteus: You can see that because if you force the transaction to get committed, then 
the Twill-based tests pass.
[8:23pm] paulproteus: So there's probably some way to make the Twill-based test suite do the right 
thing here.
[8:23pm] mandarg: did you see that?
[8:23pm] paulproteus: And it's probably a regression in our test suite caused by a Django upgrade at 
some point.

-------------------------------------------------------------------------------------

I believe the import of all this is that there are two ways to possibly fix this.

1. Abandon twill entirely, and use something like django-webtest instead 
(<a href="https://pypi.python.org/pypi/django-webtest">https://pypi.python.org/pypi/django-webtest</a>)

2. Use something like <a href="http://pythonhosted.org/django-test-utils/,">http://pythonhosted.org/django-test-utils/,</a> which might fix the problems with 
twill.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>The best path forward, given how crazy this is, is to stop using Twill's API, and 
for each of these tests that are failing, work to reimplement just enough of the 
Twill API without using the Twill WSGI wrapping stuff.

Sorry if that's vague. I can clarify more.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/Aaron1011/'>Aaron1011</a>:</b><dl><dd>Is anyone currently working on this?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>(UNKNOWN CHARACTER)I think no one is!
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file687/unnamed by paulproteus</b>

Status: <b>in-progress</b>
Nosy List: <b>  jwm, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>889</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue889'>view archived page</a>)
Last modified: <b>2014-06-10.03:16:59</b>

**Comment by willingc** [comment]
Long overdue but I was able to get the tests running on my Ubuntu system using MySQL.
Some of the existing tests are failing and a number have errors. I did need to make modifications to one of the migrations and to the settings file to get the tests to run. I plan on doing a diff later and a PR up to this point before I start trying to resolve the failing tests.

![mysql_tests](https://cloud.githubusercontent.com/assets/2680980/6873586/948faa76-d46e-11e4-8f80-46d2ebc97412.png)

**Comment by willingc** [comment]
Notes on setting up the MySQL configuration on local system (for docs later)

Install mysql-client and mysql-server on Ubuntu.
After setting up local mysql config for your  set up for oh-mainline.
At command prompt, enter `mysql`
At mysql prompt, enter `USE oh_milestone_a`
*This is case sensitive*

At mysql prompt, enter:
```
GRANT ALL PRIVILEGES
ON oh_milestone_a* to 'oh_milestone_a'
IDENTIFIED BY 'ahmaC0Th'
WITH GRANT OPTION;
```

**Comment by ehashman** [comment]
Is this fixed now, @willingc? I had assigned it to myself to remind myself to review the pull requests, but they appear to all be merged.

**Comment by ehashman** [comment]
I think this is fixed. Indeed, we've moved from MySQL to Postgres, so it's no longer applicable!
