### ISSUE TITLE
Get feedback on openhatch.readthedocs.org from a contributor, and improve it

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1206]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Shauna suggests we improve it. I wasn't sure precisely how we should improve it, 
beyond the specific bug I filed about CSS, so probably we would benefit from 
interviewing someone who's used the docs recently so we can make a change that 
would make it easier to find what they were looking for.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/anurag619/'>anurag619</a>:</b><dl><dd>I recently read the docs and have submitted a pull request for review (regarding
the CSS). I was able to find most of the things in the doc, although some more
information about the blog page "Wordpress theming"can be appreciated.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  anurag619, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>891</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue891'>view archived page</a>)
Last modified: <b>2014-02-28.06:42:35</b>

**Comment by ehashman** [comment]
This is a super vague issue and I'm wondering if we can close it in favour of more specific issues. For what it's worth, many great changes to the docs have been made since it was last modified (Feb. 2014)

**Comment by anurag619** [comment]
From what I can remember, the request was merged.

**Comment by ehashman** [comment]
Okay, I am going to close this then, as there is nothing specifically actionable here and you seem to have already addressed it in some way!
