### ISSUE TITLE
Document how to install GeoLiteCity

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1235]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd><a href="http://openhatch.readthedocs.org/en/latest/search.html?">http://openhatch.readthedocs.org/en/latest/search.html?</a>
q=geolitecity&amp;check_keywords=yes&amp;area=default

should link to

<a href="http://dev.maxmind.com/geoip/legacy/install/city/">http://dev.maxmind.com/geoip/legacy/install/city/</a>

plus explain how to use a local settings file and/or link to that.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>This is purely a documentation bug, but probably we won't have to solve this!

There are some outstanding pull requests that will, eventually, allow us to 
remove the functionality in the code that depends on GeoLiteCity at all, which 
would then mean we would never have to document our use of GeoLiteCity!

Links to those pull requests, at the time of this writing:

* <a href="https://github.com/openhatch/oh-mainline/pull/233">https://github.com/openhatch/oh-mainline/pull/233</a>

* <a href="https://github.com/openhatch/oh-mainline/pull/227">https://github.com/openhatch/oh-mainline/pull/227</a>
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/individuwill/'>individuwill</a>:</b><dl><dd>Removed python reverse geocoding.

<a href="https://github.com/openhatch/oh-mainline/pull/245">https://github.com/openhatch/oh-mainline/pull/245</a>
   
</dl></dd><hr/>

Status: <b>need-review</b>
Nosy List: <b>  individuwill, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>920</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue920'>view archived page</a>)
Last modified: <b>2014-04-20.17:52:10</b>

**Comment by willingc** [comment]
Closing this issue. Please refer to PR #245.
