### ISSUE TITLE
Mission: Using Subversion pt. 4 error

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1250]
<b>Comment by <a href='https://openhatch.org/people/narroo/'>narroo</a>:</b><dl><dd>For the final part of the training mission "Using Subversion" you are required
to commit a change to an entire directory.  The instructions tell you to change
the word "red" to "blue" in the readme file and the word "midnight" to
"Plenipotentiary" in the word.txt file.  

Attempting to commit these changes results in an error associated with the
README file:

    Commit failed (details follow):
    Commit blocked by pre-commit hook (exit code 1) with output:

        The new content of README is incorrect.

    Error: The commit failed to validate.
    This error was generated by a custom hook script on the Subversion server.
    Please contact your server administrator for help with resolving this issue.

The SVN works just fine for the word.txt file, so I believe there might be a
typo somewhere associated with the word "blue."
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/tianyupu/'>tianyupu</a>:</b><dl><dd>I just managed to complete the mission (following the mission instructions 
carefully) without getting the error that you did. narroo, could you please paste 
the contents of your svn diff here? That would help narrow things down. :)

Also, there have been reports of a very similar issue in 
<a href="http://forum.openhatch.org/discussion/20/svn-commit-fails-with-message-commit-">http://forum.openhatch.org/discussion/20/svn-commit-fails-with-message-commit-</a>
blocked-by-pre-commit-hook-exit-code-1-with-no-output/ and that was fixed by 
adding a message to the commit... so we need to test whether the presence/absence 
of a commit message causes the test to fail (despite making the correct changes).
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  narroo, paulproteus, tianyupu </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>935</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue935'>view archived page</a>)
Last modified: <b>2014-03-09.12:50:48</b>

**Comment by willingc** [comment]
Closing this issue. Refer to #1709 for subversion mission information.
