### ISSUE TITLE
strange result from canceling an openid request

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1253]
<b>Comment by <a href='https://openhatch.org/people/2mas/'>2mas</a>:</b><dl><dd>I was shown a strange looking page when trying to login to OpenHatch and then realizing my 
girlfriend was signed on to google at the time. The page looks functional but is a bare form with 
no style or OpenHatch content.

To reproduce this:
 1. Be signed in to a google account that does NOT have a profile setup with OpenHatch.
 2. Click login/signup on openhatch.org/
 3. Choose the Google account option
 4. When asked for permission for Google to provide the email address of the account click cancel 
     (this is where I realized I should sign into my Google account before continuing.)

I'm not sure whether or not this bug is caused by OpenHatch's openid code, or google/openid.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/tianyupu/'>tianyupu</a>:</b><dl><dd>I had a look at this, and I have found the issue, but being new to django and web dev, 
I wasn't sure of the best way to fix the problem. I have created a PR that fixes the 
issue, though, so that when the signup is cancelled, the login page is displayed again 
as you would expect: <a href="https://github.com/openhatch/oh-mainline/pull/214">https://github.com/openhatch/oh-mainline/pull/214</a> I'm very open 
to feedback about the best way to fix this, though :)

The issue is that when the OpenID signup is cancelled, django renders the 
authopenid/signin.html template (which is what is referred to in 
vendor/packages/django-authopenid/django-authopenid/views.py) as a result of a request 
to openid/signin (which urls.py tells us points to the signin function in the views.py 
file mentioned above). If you look at authopenid/signin.html (located in 
mysite/accounts/templates), it is the barebones page that 2mas saw.
   
</dl></dd><hr/>

Status: <b>need-review</b>
Nosy List: <b>  2mas, paulproteus, tianyupu </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>938</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue938'>view archived page</a>)
Last modified: <b>2014-03-09.08:24:57</b>

**Comment by ehashman** [comment]
#214 is now merged so I'm going to close this.
