### ISSUE TITLE
Tutorial/Process description "Add User/Project"

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1338]
<b>Comment by <a href='https://openhatch.org/people/dirkbaechle/'>dirkbaechle</a>:</b><dl><dd>There currently doesn't seem to exist a simple description about which steps are 
required to add yourself as "User" and also your "Project" to OpenHatch.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  dirkbaechle, ehashman, paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>1023</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue1023'>view archived page</a>)
Last modified: <b>2014-07-29.21:26:16</b>

**Comment by shriyanka** [comment]
Hi,
I have written description regarding the following issue #1338 and I want your feedback regarding the same. If its wrong please do correct me.
the link is : https://github.com/shriyanka/oh-mainline/blob/master/docs/tutorials/add_user_project.rst
Its my first time and I don't know whether its a good way to post the link here. If its not then ignore it this once. 

Thanks,
Kajal Gupta

**Comment by willingc** [comment]
@shriyanka submitted a pull request #1555 to address this issue and issue #1550. Thank you!

I have updated the issue status and will review the pull request and comment. Thanks :)

**Comment by shriyanka** [comment]
willingc@ thanks for viewing it :)

**Comment by SanketDG** [comment]
This can be closed?

**Comment by ehashman** [comment]
Looks that way.
