### ISSUE TITLE
Adjust test fixtures so they load properly on MySQL

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1342]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>When running the tests with MySQL, I see some messages that indicate that our 
test fixtures don't load properly.

On Travis-CI's output, e.g. within the following test:

ERROR: test_show_no_bugs_if_no_query (mysite.search.tests.SearchResults)

I see:

ValueError: Problem installing fixture '/home/travis/build/openhatch/oh-
mainline/mysite/search/fixtures/bugs-for-two-projects.json': The database 
backend does not accept 0 as a value for AutoField.

I don't know which field it's troubled by, but if it's unhappy, a bunch of tests 
sure are going to be unhappy.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>1027</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue1027'>view archived page</a>)
Last modified: <b>2014-08-04.02:02:58</b>

**Comment by ehashman** [comment]
I'm not sure exactly what PRs fixed this, but as I recall @willingc made these work! Closing.
