### ISSUE TITLE
Add a link on bug set creator edit page to send user to the list view of the set

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1385]
Right now, I've been navigating between the two views by removing `edit/` from the URL. This isn't very user-friendly.

**Comment by sri-teja** [comment]
Hello all,
I want to work on this. Can anyone suggest me how to proceed?

**Comment by sunilkumarc** [comment]
Hi experts, 

I'm working on this feature. So i wanted to include some styles for a div element in that particular page. So I wanted to know, if i'm allowed to use inline style or should i write the style properties in the main /static/packed/openhatch.css file ? Or is there any other stylesheet file I should use ?

Thanks,
Sunil

**Comment by paulproteus** [comment]
Once you run the app locally, you should see that the page includes a lot
of *.less and *.css files. You should edit those.

Hope this helps; let me know if so or if not!

**Comment by ehashman** [comment]
Hi @sunilkumarc, changes should probably be made to [this template](https://github.com/openhatch/oh-mainline/blob/master/mysite/bugsets/templates/edit_index.html). I think adding a "View Live Bugset" button as specified by @paulproteus would be the easiest fix.

**Comment by sunilkumarc** [comment]
I have fixed this issue. This is the merged pull request 
https://github.com/openhatch/oh-mainline/pull/1583. 

This issue can be closed.

**Comment by ehashman** [comment]
Great!
