### ISSUE TITLE
Check that unittest-xml-reporting is included and it is correctly configured

### ISSUE THREAD

**Issue by willingc** [openhatch/oh-mainline#1392]
py.test indicates that `import xmlrunner.extra.djangotestrunner` 
found in `oh-mainline/mysite/testrunner.py` is not being done.

https://github.com/xmlrunner/unittest-xml-reporting

**Comment by moijes12** [comment]
I have proposed a fix. Please somebody add the label stat:need-review because I unable to do that.

**Comment by willingc** [comment]
@moijes12 Thanks for the fix and I have updated the label status.

**Comment by ehashman** [comment]
Pull request has been merged so I am going to mark this as resolved. @paulproteus, hope you are satisfied with the fix!
