### ISSUE TITLE
500 Error in svn mission

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1399]
I attempted to start the svn mission and got the following error (on my local deployment):

```
OSError at /missions/svn/resetrepo

[Errno 2] No such file or directory
```

**Comment by jbpend** [comment]
I have this issue also, but it only seems to happen when I submit the correct inputs.  Incorrect inputs correctly produce the "wrong info submitted" error.

**Comment by willingc** [comment]
@jbpen Thank you for sharing your experience with this issue. My apologies for the issue on the mission, and I appreciate your time in filing this. :penguin: 

If you have any interest in trying to work on debugging this issue, please leave a message here. Happy new year!

**Comment by willingc** [comment]
@ehashman @paulproteus I could use your expertise on resolving this 500 issue.

When `DEBUG=True` in `settings.py`, the mission works correctly. When `DEBUG=False` in `settings.py`, the static files do not render correctly which I believe is a combination of Cloudflare and the difference between `settings.py` and `deployment_settings.py`. 

If you have any thoughts on which settings to change, I would be happy to give it a shot. Thanks!

PS Happy New Year!

**Comment by willingc** [comment]
Closing this issue since all seems resolved after the latest merge.
