### ISSUE TITLE
Git Training Mission: Repository could not be found for clone

### ISSUE THREAD

**Issue by Evnsan** [openhatch/oh-mainline#1436]
Hi all,
I'm trying to complete the mission but this
"git clone https://openhatch.org/git-mission-data/git/evnsan git_missions"
command returns an error:
"fatal: http://openhatch.org/git-mission-data/git/evnsan/info/refs not found: did you run git update-server-info on the server?"

I tryed to access the page directly from browser, but all I got back was a 404 error code.
It is a real issue? I talked to people on IRC channel, and they brought me here.
I hope that this report helps.

**Comment by dgmouris** [comment]
Hi Guys,

Don't know if this is an already resolved but I still get this error:

git clone https://openhatch.org/git-mission-data/git/myuser git_missions
Cloning into 'git_missions'...
fatal: unable to access 'https: .......url ...../': error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Let me know if this helps or if this is the same issue.

Cheers, 

Dan

**Comment by ehashman** [comment]
This could possibly be a server/deployment problem. Paging @paulproteus.

**Comment by dgmouris** [comment]
I think you might be right, might be a cloudflare problem, as I feel like this is another person has had this problem on cloudflare:

https://gitlab.com/gitlab-com/support-forum/issues/184

**Comment by paulproteus** [comment]
Hi dgmouris,

Can you tell me what operating system you're using? If it's a version of
Windows earlier than 7 (for example, Vista or XP) you are likely to have
problems, I'm afraid.

**Comment by dgmouris** [comment]
I am using windows 7 ,and a bash git shell to clone the repo.

**Comment by dgmouris** [comment]
I'd love to help out in any way with the code as well, if you need it:)

**Comment by paulproteus** [comment]
dgmouris, good to know. Can you try this version of Git for Windows?
https://github.com/msysgit/msysgit/releases/

and see if the problem goes away?

If so, that'll be great to know.

**Comment by dgmouris** [comment]
Hey Paul,

just used that version of git for windows and the problem doesn't seem to go away.

The exact same cloning problem as cited above happens.

Cheers,

Dan

**Comment by dgmouris** [comment]
Let me know if there's anything I can do to help:)

**Comment by willingc** [comment]
@dgmouris Thanks for following up on this issue and trying to get the clone to work with Windows 7.

A couple of questions:
1. Perhaps the obvious question but I will ask anyway: when running the `git clone` command, you specified your username. Correct? I assume that you did; otherwise, I would expect a different error.
git clone https://openhatch.org/git-mission-data/git/willingc git_missions

2. What version of OpenSSL is running on your system? If you type `openssl version` at a bash prompt, it should return the version. (As an aside for @paulproteus, I am able to clone on Mavericks 10.9.5 with OpenSSL 0.9.8zd 8 Jan 2015)

Since it appears to be a handshaking issue between the Windows 7 system and OpenHatch/Cloudflare, I wonder if updating the Windows 7 machines OpenSSL would help. (That said, I'm sorry that I have no idea how to do that on Windows).

**Comment by willingc** [comment]
A bit more research... I ran the Qualsys SSL Server Test on openhatch.org (https://www.ssllabs.com/ssltest/). 

![screen shot 2015-05-27 at 11 32 45 pm](https://cloud.githubusercontent.com/assets/2680980/7853913/ea370fca-04c8-11e5-8f12-fce280de3276.png)

Here's info on the supported protocols (TLS yes; SSL no). I believe the error message that @dgmouris saw mentioned SSLv3.
![screen shot 2015-05-27 at 11 35 04 pm](https://cloud.githubusercontent.com/assets/2680980/7853941/441bbc66-04c9-11e5-9c04-4b58e0dab068.png)

Just as an FYI, the following is part of the results from the Handshake test:
![screen shot 2015-05-27 at 11 35 30 pm](https://cloud.githubusercontent.com/assets/2680980/7853956/6d562f58-04c9-11e5-977c-ca48118859c1.png)

**Comment by BobBaig** [comment]
Any progress on this issue?  I too have Windows 7.   Following OpenHatch directions to a T: https://openhatch.org/missions/git/checkout
Getting the same SSL v3 error message:
fatal: unable to access 'https://openhatch.org/git-mission-data/git/bobbaig1/':
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
% openssl version
OpenSSL 0.9.8zf 19 Mar 2015

**Comment by willingc** [comment]
@BobBaig Thanks for the update and the workaround.

@paulproteus: My recommendation would be to update the mission instructions to recommend that Windows 7 users use http if the https commands are not working with their version of OpenSSL. Thoughts?

**Comment by paulproteus** [comment]
If http:// works, but https:// doesn't, I think it's OK in this case to
have people use http:// . Good idea, even if a slightly sad one, Carol!

**Comment by dgmouris** [comment]
The http works for me as well thanks @BobBaig @paulproteus and @willingc !

**Comment by ehashman** [comment]
I'm going to close this, given that things are looking resolved (at least via workaround :) )
