### ISSUE TITLE
Robots.txt is disallowing all crawling

### ISSUE THREAD

**Issue by brittag** [openhatch/oh-mainline#1443]
On http://openhatch.org/robots.txt, I don't think this is intentional:

> User-agent: *
> Disallow: /

I assume we want search engines to crawl at least most of the site and make it easy to find for people interested in contributing to open source. :)

This seems to have changed relatively recently - in June it allowed pages to be crawled, since I referred to Internet Archive copies in my [Merge Stories post](http://mergestories.com/s/improving-a-project-homepage/) published then. I'm guessing the task is to figure out why it changed as well as fixing it.

**Comment by ehashman** [comment]
I'm going to mark this as resolved given the fix in #1588.
