### ISSUE TITLE
Remove unused Link_SF_Proj_Dude_FM model

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-mainline#1476]
In `mysite/profile/models.py`, there is a Django "model" (which is Python code representing a kind of data we can store in the database) that is simply unused. Namely:

`Link_SF_Proj_Dude_FM`

To reproduce this bug:

* Get a copy of the code

* Confirm to your satisfaction that the code is indeed unused (note that yes, it's used in "migrations", but these are merely configuration files that indicate how to set up the app, so it's OK if it's unused there)

To fix this bug:

* Delete that class from the `models.py` in question

* Run the tests and make sure they still pass (or submit a pull request and let the autobuilder run the tests)

**Comment by willingc** [comment]
Closed by PR #1483. Thank you @arindampradhan :penguin:
