### ISSUE TITLE
Add a new section to the Basic Testing Documentation (Test Output detail)

### ISSUE THREAD

**Issue by willingc** [openhatch/oh-mainline#1479]
Django and Python support a verbosity level (the level of detail output) for running tests. By adding a `-v` flag to the command, you can control the level of detail output.

Here is the current Basic Testing documentation: http://openhatch.readthedocs.org/en/latest/getting_started/testing_basics.html

Add a section after "Running a subset of tests", suggested title "Controlling detail of test output".

If you run `python manage.py -v2 test`, a more descriptive output will be displayed.

**Comment by vipul-sharma20** [comment]
can I take this issue if no one is working on this ? I would love to help

**Comment by paulproteus** [comment]
Hi @vipul-sharma20 , thanks for commenting!

Hi @akkikumar72 -- are you still interested in working on this?

If we don't hear from you within 4 days, then we'll assume you're happily busy with other things. It's fine either way.

Cheers,

Asheesh.

**Comment by vipul-sharma20** [comment]
@paulproteus now can I take this issue ?

**Comment by willingc** [comment]
@vipul-sharma20 Thank you for adding this to OpenHatch's documentation. :penguin:

@akkikumar72 Thanks for the initial work on this issue. We welcome you to contribute as you are able on future OpenHatch issues. :penguin:
