### ISSUE TITLE
Link to "Contribute" is broken

### ISSUE THREAD

**Issue by blairg23** [openhatch/oh-mainline#1506]
When I clicked the link found at http://imdbpy.sourceforge.net/development.html#contribute , I was sent to https://openhatch.org/+projects/IMDbPY , which resulted in a 404 error.

**Comment by moijes12** [comment]
I'd vote for an upstream fix given that I'd fixed this with https://github.com/openhatch/oh-mainline/pull/1429

**Comment by ehashman** [comment]
Okay. I am going to close this as not applicable. Thanks for your report, @blairg23 !
