### ISSUE TITLE
Adding a resolving conflicts and rewriting history doc.

### ISSUE THREAD

**Issue by arindampradhan** [openhatch/oh-mainline#1514]
It would be great if we have a rewriting history and resolving conflicts docs.It will be helpful when a pull request needs modification .That would surely help people new to the project get to know the importance of pull request and version control .

Being new to version control system the few things I got to know about git:
* It is not a file tracker but a content tracker (it **does not track empty files** in your git repository)
* Each commits has a **hash value**(SHA-1) which is **fixed**.
* Commits **do not** technically **change** when we force push the commit while modifying it. But the **hash gets updated** ,and the new hashed commit gets tagged to that branch.You can easily find you previous commit on github too ( if you remember the hash ).  
* Commits are always fixed(with hash) but **branches are relative** and if we **git rebase -i HEAD~num** (num refers to the number of previous HEAD),we can see the commands that are run on that branch which eventually shows up on your pull request and **git log**.
*So branches are technically a tagging system to commits that have a hash value and it can operate with options like squash , pick and many other* .See [this](https://help.github.com/articles/about-git-rebase/).
* Tools like [kdif3](http://kdiff3.sourceforge.net/) can help with resolving conflicts.Conflicts are essentially two or more commits from different branches which overlap cuz they have different content.So kdiff3 helps you pick that content of the commit which you want to get merged in final commit.   

Found these links to be helpful for fixing branch issues :
* https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
* https://sethrobertson.github.io/GitFixUm/fixup.html (thanks to @willingc for the link it gave me an insight view of git) .

**Comment by eeshangarg** [comment]
Hello @arindampradhan!

I recently had the opportunity to work on a couple of bugfixes for the [Sahana Eden project](http://eden.sahanafoundation.org/) as a part of my Google Code-In 2015 assignments; and one thing I like about their contributor documentation is that they have a [page](http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/Git) on their wiki that is completely devoted to Git workflows that give you a good idea of what to do when running into conflicts, squashing commits, cherry-picking, working with different branches, etc.

[Lynn Root](http://www.roguelynn.com/), has written an [amazing introduction to Git](http://newcoder.io/begin/save-your-progress/) as a part of her [New Coder project](http://newcoder.io/), and I think that this is a great introduction to Git for people new to programming and version control. Also, one thing I would like to say about the New Coder tutorials, they're AMAZING! :-)

Also, after getting used to these workflows, if someone really wishes to study Git in depth, I would say that [Pro Git by Scott Chacon](http://git-scm.com/book/en/v2), is worth perusing. It is also a very handy reference. I am currently going through it and as someone relatively new to version control and to the programming world in general, it has definitely made me more confident about my Git skills.

In my humble opinion, I am doubtful as to whether we should document frequently used Git workflows or the details of how hash values work ourselves, as there are already many great external resources(the ones above and the ones that you suggested, thanks a lot for that! :-) ) that address this and do an excellent job of describing different Git workflows for different scenarios. I personally think that links to these resources in the [Contributor Guide](https://openhatch.readthedocs.org/en/latest/getting_started/getting_started.html) or maybe in a separate document should suffice, however, I can be wrong about this, and I apologize if I am.

I would really appreciate it if someone could give some feedback and guidance as to how to move further with this issue. :-)

Happy New Year!

Regards,
Eeshan Garg

**Comment by ehashman** [comment]
I would agree with Eeshan: a lot of excellent documentation exists elsewhere and there's no need to reinvent the wheel, but it would be good to provide more guidance in our docs for newbies. +1 to linking offsite resources in our documentation.

Another thing I thought of is the creation of an "advanced" git training mission that requires the use of these skills, e.g. squashing commits and tracking upstream repos---beyond git add, push/pull, and commit. What do you think of that, @eeshangarg and @arindampradhan?

**Comment by arindampradhan** [comment]
@eeshangarg and @ehashman creating a git training mission for that looks a great idea to me...I could n't agree more.... :) ..I think introducing tools like kdiff3 to people will be great though.... :)

**Comment by willingc** [comment]
@arindampradhan,@eeshangarg, and @ehashman: It would be awesome to condense the good info from this thread and create a contributor doc perhaps under the Advanced section https://github.com/openhatch/oh-mainline/tree/master/docs/advanced

'Working with git' or something like that could be a title. It doesn't have to be long. Just introducing kdiff3 and other links would be great.

Anyone interested in doing this?

**Comment by arindampradhan** [comment]
@willingc ya sure :) ,that would be great..I would like to work on it.
 Just concluding happy new year to all :D  http://xkcd2.com/1296/ found a xkcd link on that ;)

**Comment by willingc** [comment]
@arindampradhan Cool. Thanks for the comic too :laughing:

**Comment by arindampradhan** [comment]
@willingc I have added the docs for git ,please suggest changes if required :)

**Comment by eeshangarg** [comment]
Hi @ehashman!

Here are my thoughts on an advanced Git training mission:

In my humble opinion, if the mission is supposed to be non-interactive, then I think links to the relevant external resources in our Contributor Guide as well as at the end(quick reference) of the existing Git training mission should suffice, but again, due to lack of knowledge and experience, I can be wrong about this. On the other hand, if we can make the mission interactive, then I personally can't wait to go through it as it seems like something that would be a lot of fun to work on and implement.

@ehashman, should I go ahead and file a separate issue about the advanced Git training mission and start a conversation about it there?

Also, I think we really need an IRC mission(someone is already working on this, I think) and a Mercurial training mission. A lot of projects use Mercurial(for example CPython, PySoy, etc) and I think it would be awesome to have a mission dedicated to Mercurial basics.

Let me know what you think! :-)

Warm regards,
Eeshan Garg

**Comment by ehashman** [comment]
@eeshangarg wrote:
> In my humble opinion, if the mission is supposed to be non-interactive, then I think links to the relevant external resources in our Contributor Guide as well as at the end(quick reference) of the existing Git training mission should suffice, but again, due to lack of knowledge and experience, I can be wrong about this. On the other hand, if we can make the mission interactive, then I personally can't wait to go through it as it seems like something that would be a lot of fun to work on and implement.
>
> @ehashman, should I go ahead and file a separate issue about the advanced Git training mission and start a conversation about it there?

I agree, Eeshan! While I think the docs that @arindampradhan is writing are very valuable, I think it would be equally valuable to create an interactive mission to test out one's skills. I think you should file a separate issue for the advanced git training mission.

> Also, I think we really need an IRC mission(someone is already working on this, I think) and a Mercurial training mission. A lot of projects use Mercurial(for example CPython, PySoy, etc) and I think it would be awesome to have a mission dedicated to Mercurial basics.

I'm not 100% sure about Mercurial, but I'm pretty sure an IRC mission has already been filed. You can check by doing a search on label:missions.

Cheers!

- e
