### ISSUE TITLE
Fully remove populate_icon_from_ohloh() method, and all the code that supports it

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-mainline#1524]
Right now, we have some code in `mysite/customs/ohloh.py` that supposedly downloads project icons from Ohloh.net. However, we seemingly never actually call this code. Therefore, we should delete it.

*More details*

Historically (see e.g. #510 ), when saving a new project from the portfolio editor, the `oh-mainline` code would talk to `ohloh.net` to try to find an icon for the project.

However, upon my manually testing in on a code checkout on my laptop, when saving a project named "wordpress" via the profile editor, we use the default icon.

Upon adding a `pdb.set_trace()` to the `populate_icon_from_ohloh()` method, I cannot trigger the `python manage.py runserver` blocking in the debugger -- which suggests we just never call this function from the profile editor. Using `git grep populate_icon_from_ohloh` seems to confirm this.

*Therefore*

Let's just delete this code. It is confusing and not helping anybody anymore.

The positive benefits from this old code will live on, in that there are some icons that were correctly selected in the deployment. So we can still be glad we _had_ the code even if we remove it so we don't have the code going forward.

**Comment by arindampradhan** [comment]
Hi @paulproteus, I would like to work on this:

On ``$ git grep populate_icon_from_ohloh``

    mysite/customs/tests.py:    def test_populate_icon_from_ohloh(self):
    mysite/customs/tests.py:        project.populate_icon_from_ohloh()
    mysite/customs/tests.py:    def test_populate_icon_from_ohloh_uses_none_on_no_match(self):
    mysite/customs/tests.py:        project.populate_icon_from_ohloh()
    mysite/customs/tests.py:        proj.populate_icon_from_ohloh()
    mysite/search/migrations/0014_populate_icons_for_existing_projects_LATER.py:            model_project.populate_icon_from_ohloh()
    mysite/search/migrations/0014_populate_icons_for_existing_projects_LATER.py:            # populate_icon_from_ohloh doesn't exist anymore.
    mysite/search/models.py:    def populate_icon_from_ohloh(self):

I have a question:
Is deleting migration file ``mysite/search/migrations/0014_populate_icons_for_existing_projects_LATER.py`` fine or do I need to add other migrations for the following changes... ??

**Comment by paulproteus** [comment]
Hi @arindampradhan !

On one hand, it's usually good to let the migrations stay the way they are.

On the other hand, in this case, if we leave the migrations the way they are, they won't run -- `model_project.populate_icon_from_ohloh()` will raise `AttributeError`.

So in this case, you should change the migrations. Glad you asked!

**Comment by thequbit** [comment]
I believe #1530 closes this, correct @paulproteus,  @arindampradhan?  Can it be closed?

**Comment by arindampradhan** [comment]
yaa sure :) @thequbit
