### ISSUE TITLE
change "expand" to "collapse" when a bug is expanded

### ISSUE THREAD

**Issue by vipul-sharma20** [openhatch/oh-mainline#1536]
When any search result is expanded by clicking on `expand` the text should change to `collapse`

![expand](https://cloud.githubusercontent.com/assets/5447064/6017154/07d64350-abb1-11e4-891a-0c42db0e5d87.png)

**Comment by ehashman** [comment]
@vipul-sharma20: I recommend you take a look at the recommended fix in #1035; not sure if it's still relevant but it couldn't hurt.

**Comment by pdurbin** [comment]
Just a heads up that @moijes12 might take a look: http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-05-23#i_3635838 (thanks!)

**Comment by dgmouris** [comment]
@pdurbin @ehashman I was wondering if you guys still need help with this and if I can help out.

**Comment by moijes12** [comment]
@dgmouris Thanks. It would be great if you could look into this. I tried it but couldn't get far as I don't know much about JavaScript.

**Comment by dgmouris** [comment]
@moijes12 I still need to set up my environment and stuff (hopefully in the next few days), but I could help you out as well if you'd like as I have some experience with javascript and jquery.

**Comment by moijes12** [comment]
Thanks @raissaa . Someone, please change the status of this ticket to needs-review

**Comment by willingc** [comment]
Thanks @raissaa and @moijes12. I've updated the status :)

**Comment by willingc** [comment]
And updated the status to resolved. Sorry missed the recent merge.

@raissaa Thank you for the contribution :penguin: If you have not already submitted an contribution email permitting us to share your work http://openhatch.readthedocs.org/en/latest/getting_started/handling_contributions.html#permit-us-to-share-your-work, please do so.

**Comment by raissaa** [comment]
@willingc Oh sorry, I forgot about that, but will do. Thanks. :smiley:
