### ISSUE TITLE
Intro For Developers link is broken

### ISSUE THREAD

**Issue by SarahRK** [openhatch/oh-mainline#1552]
At the bottom of this page:
https://openhatch.org/

There's a link that says "Intro for developers":
http://openhatch.readthedocs.org/en/latest/README.html

Which shows an error message:
"You've found something that doesn't exist."

**Comment by willingc** [comment]
@SarahRK Thanks for reporting this issue :)

For anyone that wishes to work on this, here is a suggested fix:
http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-03-09

**Comment by anurag619** [comment]
I would like to fix this.

**Comment by willingc** [comment]
@anurag619 Thanks for offering to fix. I didn't see that there was already an open PR to fix the issue. I've merged the fix.
