### ISSUE TITLE
Clarity could be more user friendly on CONTACT US

### ISSUE THREAD

**Issue by TamaraYWashington** [openhatch/oh-mainline#1563]
Chat with us on IRC
![screen shot 2015-03-21 at 3 35 51 pm](https://cloud.githubusercontent.com/assets/11082473/6766541/6ed8be90-cfe0-11e4-855e-bf93fb302684.png)

**Comment by willingc** [comment]
@TamaraYWashington Thank you for submitting this issue. OpenHatch wants to give our users a great documentation experience. Thanks for helping the next person :)
