### ISSUE TITLE
Merde: there was an error saving your ordering

### ISSUE THREAD

**Issue by elifarley** [openhatch/oh-mainline#1567]
I'm unable to sort my projects. When I click **Save this ordering**, I get an alert with this message:

>Merde: there was an error saving your ordering

**Comment by willingc** [comment]
@elifarley Thanks for reporting this issue. If you can provide a bit more detail that would be helpful. Thanks!

**Comment by ehashman** [comment]
I've discovered the [source of this alert](https://github.com/openhatch/oh-mainline/blob/master/mysite/static/js/importer.js#L1036). The bug likely is in that file.

**Comment by ehashman** [comment]
Thanks @Deborah-Digges for fixing this!
