### ISSUE TITLE
500 Errors on everything due to DEBUG=False in settings.py

### ISSUE THREAD

**Issue by chums923** [openhatch/oh-mainline#1576]
I'm just making this issue because the docs say to link any PR with an issue. Not sure if it's actually necessary, though. 

I've already made the fix and will be submitting a PR shortly.

**Comment by paulproteus** [comment]
Hi @chums923 ! Thanks for submitting this, and I saw a bit of the IRC chatter too.

I think it'll be great to make this change; I do think we should make sure that `deployment_settings.py` (which is what is used on the live site) uses `DEBUG=False`, per Django's security recommendations.

Have you verified that `deployment_settings.py` sets `DEBUG=False`, and that the app basically works in that configuration? If not, I figure we should do that before merging this. Happy to take other opinions though.

**Comment by chums923** [comment]
Hi @paulproteus! Thanks for commenting. Yes, so  `deployment_settings.py` still does set `DEBUG=False`.

As for whether that app works, do you mean can I run it locally? The answer to that is yes, and I can't if `DEBUG=False` in `settings.py`. If you're talking about something else, then I'm afraid I have no idea.

**Comment by willingc** [comment]
@chums923 There are two files: `settings.py` and `deployment_settings.py`. 

When you are running Django on your local system, Django uses `settings.py` and for development `DEBUG=True`.

When we deploy OpenHatch to a live server, the `deployment_settings.py` file is used. For security reasons, we set `DEBUG=False` for the live server deployment.

Thanks for submitting the issue. It's helpful to create the issue and a pull request. This way, future developers will have some background on the code change without cluttering up the log history :)
cc/@paulproteus

**Comment by shaunagm** [comment]
Thanks so much, @chums923!  I've deployed the change to the live site.  :)
