### ISSUE TITLE
Remark on the purpose of "vendor" in the docs

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-mainline#1580]
@shaunagm remarked to me that the `vendor` directory can be confusing to people using github code search online.

**Comment by shaunagm** [comment]
So I think we can leave a remark there that the inclusion of the vendor directory makes it difficult to search the web, and that you probably want to go to /mysite directory on the command line and type "git grep $search_term" instead.  That said, we should probably have that information more prominently.  Maybe an "unstick yourself" section of the "getting started guide" could include tips and hints like this?

**Comment by willingc** [comment]
@shaunagm and @paulproteus: Good suggestion to add to the docs to grep on the terms from the command line. 

GitHub Search does provide options for customizing the search. Search syntax gives much flexibility https://help.github.com/categories/search/ So it's probably worth mentioning as well.

**Comment by CleoQc** [comment]
Working on it. 
I'm adding  $search-term -path:vendor as a trick to avoid the vendor directory from within github.

**Comment by ehashman** [comment]
Such +1, @CleoQc!
