### ISSUE TITLE
User is able to input invalid text into the donation amount box

### ISSUE THREAD

**Issue by jlachewitz** [openhatch/oh-mainline#1581]
User is able to input invalid text into the donation amount box (empty string, letters, punctuation, etc).  This results in PayPal being very distraught and giving the user some confused error messages.  Maybe verify donation text is a valid number before redirecting user to PayPal?

![screen shot 2015-04-13 at 11 44 34 am](https://cloud.githubusercontent.com/assets/11926859/7119274/876e4200-e1d2-11e4-8031-4470894f4c47.png)

![screen shot 2015-04-13 at 11 34 11 am](https://cloud.githubusercontent.com/assets/11926859/7119183/0b0ec7ac-e1d2-11e4-9a62-3bbf714a03d1.png)

![screen shot 2015-04-13 at 11 42 37 am](https://cloud.githubusercontent.com/assets/11926859/7119221/3d094548-e1d2-11e4-89cc-7073001a9732.png)

**Comment by paulproteus** [comment]
Thanks to @jlachewitz for filing this! And thanks to @NPrescott for fixing it.

**Comment by ehashman** [comment]
+1
