### ISSUE TITLE
Add Project Allows for Blank Project Name

### ISSUE THREAD

**Issue by donnemartin** [openhatch/oh-mainline#1582]
When I go to the following URL and add a project:
https://openhatch.org/+portfolio/editor/

I am able to create an empty project with no project name, no entry for "Describe this project:", and no entry for "Describe your involvement:".

The empty project name is problematic because it seems the project URL is based on the project name when you view the listing of projects on:

https://openhatch.org/people/dmartin/

It could be helpful to add some input validation.

Tested OSX 10.9.5 on the following: 
-Chrome Version 41.0.2272.118 (64-bit)
-Version 7.1.2 (9537.85.11.5)
-Firefox 37.0.1

![screen shot 2015-04-13 at 11 33 31 am](https://cloud.githubusercontent.com/assets/5458997/7119396/4e8dd0ee-e1d3-11e4-8b30-b2203162c7ce.png)

**Comment by jlachewitz** [comment]
It's also possible to log two projects with the same name which prevents the user from navigating to whichever project was logged first.

**Comment by willingc** [comment]
@jlachewitz Good point. Would you mind opening a second issue for the duplicate project names and mention this issue number in the additional issue. Thanks :sunglasses:

**Comment by willingc** [comment]
@donnemartin Thank you for a well written and detailed bug report. :sunny:

**Comment by ehashman** [comment]
The duplicate project name issue is already reflected in #1046, fyi!

**Comment by greeshmab** [comment]
The database has unique name for each project,but the display name need not be unique(as per the code). The display name may be empty string. What if we make display_name and name as same?

**Comment by ehashman** [comment]
@greeshmab: That's a possibility, but I think it would make more sense to ensure that the `display_name` can't be empty. I *believe* `name` is used in URL generation, among other things, so it makes sense for them to be distinct fields.

**Comment by felipevolpone** [comment]
This is already done here: https://github.com/openhatch/oh-mainline/blob/d5b90d73e6e95034cc9106d11b46554fc99837c5/mysite/static/js/importer.js#L709. 
Can this issue be closed or move it to needs-review?

**Comment by Deborah-Digges** [comment]
You're right @felipevolpone !
This PR closes it :https://github.com/openhatch/oh-mainline/pull/1720. Thanks for spotting this :)

**Comment by donnemartin** [comment]
:+1:
