### ISSUE TITLE
Bitesize "What's this?" doesn't appear intuitively on search page

### ISSUE THREAD

**Issue by ableman** [openhatch/oh-mainline#1595]
![image](https://cloud.githubusercontent.com/assets/4017467/7145854/f80db8e8-e2a3-11e4-91ce-c2b005ebd2c2.png)

Appears all the way in the top right corner instead of where clicked. Also, cannot be reopened after being closed once

**Comment by willingc** [comment]
@ableman I agree that the placement of the definition is not ideal. More problematic for me, the "What's this?" link is only usable one time.

**Comment by MrMepper** [comment]
This seems like an easy enough bug to fix. I'll try my hand at it.(:

**Comment by ehashman** [comment]
Link is now clickable many times! How strongly do we feel about the placement, @willingc? Perhaps I'll leave it to you or @ableman to decide whether this bug is resolved now.

**Comment by MrMepper** [comment]
Alright, so I've edited around with the jGrowl.css config files, and have changed the default values of the "center" location to be placed below the "What's this?" button:

![untitled](https://cloud.githubusercontent.com/assets/8658239/8294439/510f85b8-1902-11e5-80af-0d87169def26.png)

If everyone agrees with this new location, I can make another pull request.

**Comment by ehashman** [comment]
A new concern for me is I'm noticing that the tooltip has some unexpected inner margins.  We should look into fixing that too!

I don't really have an opinion on the placement.

**Comment by jamessimas** [comment]
@ehashman,

I've taken a crack at fixing the unexpected inner margins/wrapping you mentioned. It's in pull request #1678.

**Before commit:**
![image](https://cloud.githubusercontent.com/assets/12779236/8509319/fde3e754-2251-11e5-8ec6-31f73233db33.png)

**After commit:**
![image](https://cloud.githubusercontent.com/assets/12779236/8509317/e67aa4cc-2251-11e5-9980-b23bfc9a2cfd.png)

**Comment by ehashman** [comment]
Thanks for your fix, @jamessimas! Marking this as resolved.
