### ISSUE TITLE
Widgetize yourself links to wrong location

### ISSUE THREAD

**Issue by ableman** [openhatch/oh-mainline#1597]
![image](https://cloud.githubusercontent.com/assets/4017467/7148339/f472f7f8-e2b6-11e4-9cdd-05e56af52561.png)

It says localhost, I don't think it's supposed to. I can't get the widget working, but that might just be me.

**Comment by ehashman** [comment]
Hi @ableman, are you testing this on your local deployment? When I tested this on openhatch.org, I got the following widget code:

```
<script type='text/javascript' src='http://openhatch.org/people/ehashman/openhatch-widget.js'></script>
```

as expected, and

```
<script type='text/javascript' src='http://localhost:8000/people/testuser/openhatch-widget.js'></script>
```

on my local instance.

**Comment by ableman** [comment]
Yes, it's from the live site. I also thought I might have done something like that so I double checked, and even asked Shauna to check I wasn't crazy. I've also tested this in Incognito mode, then rebooted into my Windows 7 boot (on which I don't have a local instance of openhatch) and tested again. And tested it on Internet Explorer. Same behavior for me every time.

**Comment by ehashman** [comment]
I am unable to reproduce on any browser/OS; do we have any other reports of this?

**Comment by NPrescott** [comment]
I can't reproduce this, I see the following:
```html
<script type='text/javascript' src='http://openhatch.org/people/NolanPrescott/openhatch-widget.js'></script>
```
Although I can't get the widget working either. It renders fine, but there's no content, unless it is a scheduled job or something? (example: http://nprescott.com/public/widget-test.html )

**Comment by ableman** [comment]
I'm not crazy, I swear. Here's the page from my desktop computer which I didn't take to Pycon, using a different google account in Incognito mode.

![image](https://cloud.githubusercontent.com/assets/4017467/7197698/d924b11a-e498-11e4-85af-798f76bba7cb.png)

Suggested testing behavior so that maybe someone other than me can see this. Log in as 

mycrazyfavoritedummy@gmail.com
password: dummydestroyerofdoom

See if it shows up.

**Comment by NPrescott** [comment]
At this point this is more amusing than anything, still can't reproduce (using the above credentials):

![screen shot 2015-04-17 at 3 14 36 am](https://cloud.githubusercontent.com/assets/4661088/7198266/03739f0a-e4b0-11e4-8ca3-bc2bdb0b2498.png)

In both your screenshots you don't seem to have loaded the openhatch logo in the widget, ( `<img src="http://openhatch.org/static/images/logo-for-widget.png" height="55" width="80">` ). Is that linking to `localhost` as well? Also interesting, your localhost URL is using HTTPS, while all the URLs I see are plain HTTP - this is all very curious.

**Comment by ehashman** [comment]
Okay! Good suggestion, @NPrescott. I've discovered that the localhost bug *only* occurs over HTTPS, and reproduced.

**Comment by ableman** [comment]
Confirmed. Bug only occurs when using HTTPS, not HTTP. And yes, the logo also links to localhost in that case.

**Comment by paulproteus** [comment]
​Sadly it slightly makes sense that the problem would occur over just HTTPS
and not HTTP; the way the server is set up, they're slightly different.

Huge props to all involved for narrowing that down.

I just made the following config change to
/etc/nginx/sites-available/default -- was:

server {
listen   443;
server_name  localhost;



is now:


server {
listen   443;
server_name  openhatch.org;


and just manually tested this; I think it's fixed. Can someone confirm or
deny?

**Comment by NPrescott** [comment]
Can confirm it is now working. I was also able to reproduce before the change was made.

:+1:

**Comment by ableman** [comment]
Yep. Closing this issue.
