### ISSUE TITLE
7 test Fails when run on Windows

### ISSUE THREAD

**Issue by CleoQc** [openhatch/oh-mainline#1601]
Paired with @willingc at Pycon 2015 sprints.

running Windows 8.1 and Python 2.7

======================================================================
FAIL: test_robots_with_debug_true (mysite.base.tests.RenderDevRobotsTest)
Set DEBUG to True in settings.py and verify that robots.txt contains
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\base\tests.py", line 625, in
test_robots_with_debug_true
    self.assertEqual(response.content, robots_text)
AssertionError: 'User-agent: *\r\nDisallow: /' != 'User-agent: *\nDisallow: /'

======================================================================
FAIL: test_robots_with_debug_false (mysite.base.tests.RenderLiveRobotsTest)
DEBUG is set to False by default, verify that robots.txt returns
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\base\tests.py", line 609, in
test_robots_with_debug_false
    self.assertEqual(response.content, robots_text)
AssertionError: 'User-agent: *\r\nDisallow: /search/*?*\r\n\r\nDisallow: /w/\r\n
Disallow: /wiki/Special:Search\r\nDisallow: /wiki/Special:Random\r\n' != 'User-a
gent: *\nDisallow: /search/*?*\n\nDisallow: /w/\nDisallow: /wiki/Special:Search\
nDisallow: /wiki/Special:Random\n'

======================================================================
FAIL: test_backwards_diff (mysite.missions.diffpatch.tests.DiffSingleFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\missions\diffpatch\tests.py",
 line 211, in test_backwards_diff
    'order of files passed to diff was flipped' in utf8(e))
AssertionError: False is not true

======================================================================
FAIL: test_do_mission_backwards_diff (mysite.missions.diffpatch.tests.DiffSingle
FileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\missions\diffpatch\tests.py",
 line 296, in test_do_mission_backwards_diff
    submit_response.content)
AssertionError: False is not true

======================================================================
FAIL: test_do_mission_correctly (mysite.missions.diffpatch.tests.DiffSingleFileT
ests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\missions\diffpatch\tests.py",
 line 266, in test_do_mission_correctly
    self.assert_(submit_response.context['diffsingle_success'])
AssertionError: False is not true

======================================================================
FAIL: test_patch_applies_correctly (mysite.missions.diffpatch.tests.PatchRecursi
veTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\missions\diffpatch\tests.py",
 line 540, in test_patch_applies_correctly
    self.assertEqual(tar_process.returncode, 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_with_lock_contention (mysite.customs.tests.BlogCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Cleo\Documents\oh-mainline\mysite\customs\tests.py", line 149,
in test_with_lock_contention
    self.assertEqual(entries, self.blog_fetcher_version_1())
AssertionError: 'this-data-is-also-fake' != 'this-data-is-fake'

----------------------------------------------------------------------
Ran 379 tests in 48.450s

FAILED (failures=7, errors=13, skipped=71)

**Comment by ableman** [comment]
Linking to the previous discussion about this #1380 Can probably be consolidated into one discussion

**Comment by ehashman** [comment]
Curious if @paulproteus' comments on #1380 would suggest that this kind of thing is out of scope. I kind of want to mark one of the two issues as a duplicate.

**Comment by ehashman** [comment]
Also #1213 is related.

**Comment by willingc** [comment]
Closing this issue. Any new test failures for windows should be filed as a new issue :penguin:
