### ISSUE TITLE
Update Events page to reflect current event focus

### ISSUE THREAD

**Issue by dcwalk** [openhatch/oh-mainline#1602]
The [Events](https://openhatch.org/events/) page (https://openhatch.org/events/) lists the Boston Python Workshop and Build It alongside Open Source Comes to Campus (OSCTC), is it possible to adjust this to reflect that OSCTC is primarily the active of the two?

**Comment by ehashman** [comment]
I think this would be a great bitesize bug. Here is my interpretation of @dcwalk's ask:

1. Navigate to https://openahatch.org/events/ and notice the events on the page have the Boston Python Workshops listed first, and Open Source Comes to Campus (OSCTC) second.
2. We'd prefer OSCTC to come first. To fix this, one will need to modify the static HTML of the page, which can be found at [mysite/base/templates/base/events.html](https://github.com/openhatch/oh-mainline/blob/master/mysite/base/templates/base/events.html)
3. Move the OSCTC DOM node first and submit a pull request reflecting the swap.

And feel free to let me know if you have any questions!

**Comment by shaunagm** [comment]
When adding the mentor-available tag, it's probably useful to mention who can mentor -- although "whoever added the tag" is probably a reasonable assumption.  In addition to @ehashman, I'm willing to mentor this.

**Comment by ehashman** [comment]
@shaunagm: along those lines, I would have added myself to the bug by assigning me, but then I was worried contributors might think that the bug was taken/in-progress.

**Comment by shaunagm** [comment]
I think it makes sense to just mention potential mentors in the comments - presumably someone looking for mentored bugs will read the comments.

**Comment by Deborah-Digges** [comment]
Closed by: https://github.com/openhatch/oh-mainline/pull/1626.
