### ISSUE TITLE
Introduce project tags and potentially tag clouds

### ISSUE THREAD

**Issue by CleoQc** [openhatch/oh-mainline#1606]
Tags can be attached to projects to allow for a better and searchable description. Tags can be one word descriptors like Astronomy, Healthcare, or Games.

The goal is to have a better way for newcomers to find projects that would be of interest to them, based on subject matter. 

Also, possibility of a tag cloud to get a high level view of what types of projects are in the database.

**Comment by ehashman** [comment]
Appears to be a duplicate of #751?

**Comment by willingc** [comment]
Changing status to deferred pending Strategic Technical planning decisions http://lists.openhatch.org/pipermail/devel/2015-August/003841.html :penguin:
