### ISSUE TITLE
Another misaligned subscribe button on front page, newsletter box

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1621]
This one is on the front page. I'm running FF 37.0.1 on Ubuntu.

![subscribe2](https://cloud.githubusercontent.com/assets/4706131/7202695/ae90fec8-e4e2-11e4-8c69-aab437ff424e.png)

Tangentially related to #1556.

**Comment by STashakkori** [comment]
Here's my attempt to horizontally center and beautify the Subscribe button.
https://github.com/openhatch/oh-mainline/pull/1624

**Comment by sunilkumarc** [comment]
Hi @paulproteus @shaunagm @willingc @ehashman,

I have fixed the alignment of 'Subscribe' button in the home page. This is how it looks in chrome now
![fix-1621_chrome](https://cloud.githubusercontent.com/assets/3911000/7433104/a1ad9f3a-f04b-11e4-951d-d07b63373f22.jpg)

And this is how it looks in firefox now
![fix-1622_firefox](https://cloud.githubusercontent.com/assets/3911000/7433115/b3bf39c2-f04b-11e4-88c0-9c8ed0706331.jpg)

Please let me know in case any more changes are required.

**Comment by phildini** [comment]
Fixed by #1644.
