### ISSUE TITLE
OpenID 2.0 for Google Accounts has gone away

### ISSUE THREAD

**Issue by rghamilton3** [openhatch/oh-mainline#1633]
When trying to sign up for a new user account via Google you are redirected to https://support.google.com/accounts/answer/6206245?p=openid&rd=1 which states "OpenID 2.0 was replaced by OpenID Connect, and since April 20, 2015, no longer works for Google Accounts. OpenID 2.0 support was shut down in order to focus on the newer open standard OpenID Connect, which provides greater security for your account."

**Comment by willingc** [comment]
@rghamilton3 Thanks for reporting this issue. :penguin:

**Comment by dkalaluhi** [comment]
+1 Will I be able to get my ghetto account removed once the Google auth bug is fixed :)

**Comment by paulproteus** [comment]
Sure, I can make sure we remove it when the time is right! (-:​

**Comment by paulproteus** [comment]
This is pretty important. Sorry that this is currently broken.

**Comment by pdurbin** [comment]
I've been logging into OpenHatch via Google but now I can't and I'm wondering if there is any sort of process for migrating whatever state I have saved under my Google login (partially completed missions, etc.) to a non-Google login until this is fixed.

And once it's fixed I'm curious if I'd be able to move that saved state back to my Google login. If this is all simply crazy talk, the idea of switching from one login provider to another, please let me know.

**Comment by willingc** [comment]
I found this doc while researching the issue: https://developers.google.com/identity/protocols/OpenID2Migration

Leaving this for someone @paulproteus @eeshangarg @ehashman @phildini that has more authentication experience than me.

**Comment by jpellman** [comment]
+1

**Comment by pdurbin** [comment]
Works fine now! Thanks @paulproteus!

**Comment by paulproteus** [comment]
Thanks, all. Seeing as this has been tested resolved, I'll close the issue.
