### ISSUE TITLE
Bug while Signup 

### ISSUE THREAD

**Issue by saqib-nadeem** [openhatch/oh-mainline#1635]

**Comment by willingc** [comment]
@saqib-nadeem Thanks for the issue report. Are there any more specific details that you can share? Thanks.

**Comment by saqib-nadeem** [comment]
Other-day, when I tried to sign up without open ID by filling sign up details over here => http://openhatch.org/account/signup/ showed me something like that csrf token error, However today I just gave another try it works fine :)

**Comment by willingc** [comment]
Thanks for the update @saqib-nadeem. 

Closing this issue. If anyone experiences this issue, please reopen this. Thanks.
