### ISSUE TITLE
Error: The user account associated with this email address cannot reset the password.

### ISSUE THREAD

**Issue by elifarley** [openhatch/oh-mainline#1651]
Since I'm unable to log in using Google anymore ( see #1633 ), I've tried to reset my password.

Here's the error message I've got:
**The user account associated with this email address cannot reset the password.**

**Comment by willingc** [comment]
@elifarley Thanks for the issue report. As you very correctly pointed out this issue is related to issue #1633. Once #1633 is resolved, then this issue should also be resolved. Thanks again. :penguin:

Dev team: I am marking this as a duplicate and closing this issue.
