### ISSUE TITLE
Recommend distro/OS specific commands to install pip, virtualenv, etc in the pip/virtualenv mission

### ISSUE THREAD

**Issue by eeshangarg** [openhatch/oh-mainline#1653]
Hi everyone!

I was thinking about the pip/virtualenv mission, and I thought, should we start recommending distro/OS/package manager specific commands to install pip, virtualenvwrapper, wheel etc, instead of the pip2014 script? For instance, I tried Fedora a couple of months ago and I could easily ```yum install``` all of the above mentioned tools and everything worked! Recently, I felt that I missed Debian a lot, so I installed Debian 8, and I was able to easily ```apt-get install``` the aforementioned tools and again everything worked as it should. I have also tried to ```apt-get install``` these tools on Ubuntu, Xubuntu, and Debian 7 and this approach always works. :-)

I would be willing to work on this! It would mean a lot to me if someone could give me some guidance on whether what I proposed sounds like a viable approach or not. :-)

Warm regards,
Eeshan garg

**Comment by willingc** [comment]
@eeshangarg +1 I think this would be a good idea in missions or docs :) Thanks!
