### ISSUE TITLE
Display currently deployed version

### ISSUE THREAD

**Issue by NPrescott** [openhatch/oh-mainline#1676]
##### This is a feature request

It would be helpful, in troubleshooting and bug reporting, to display the version of OH that is deployed on the live site. There are times when  deployment lags recent commits/bug fixes and there is back-and-forth on whether a fix is not working, or simply not applied yet.

As an example, Atlassian products include something similar on page footers:
![atlassian-version](https://cloud.githubusercontent.com/assets/4661088/8485630/9b206202-20c4-11e5-9c5d-3b2e9e02075c.png)

I'm thinking this could be done as part of whatever deployment script is being used presently. The information is available from git with:
```
$ git rev-parse --verify HEAD
0ebad593e7eed30f7d9e810435311827e5032d75
```
If this was set as an environment variable or written to a temp file I think it could be included in one of the templates without much difficulty.

**Comment by ehashman** [comment]
I really like this feature request/patch. Merged and closing!
