### ISSUE TITLE
Need savannah as a bug tracker

### ISSUE THREAD

**Issue by sebadiaz** [openhatch/oh-mainline#1682]
Savannah manage 3386 projects with more than 66000 users.

To recreate some dynamic, I think that we need more visibility as your site could done in the respect of the values of the Free Fundation Software and the license related.
https://savannah.gnu.org

GNA based on the same savane engine needs too
https://gna.org

**Comment by ehashman** [comment]
Thanks for your request, @sebadiaz! I'll file this for you against oh-bugimporters.
