### ISSUE TITLE
curl: Remote file name has no length!

### ISSUE THREAD

**Issue by sarbazx** [openhatch/oh-mainline#1685]
Hi, in mission diffing individual files i having error when downloading files by curl in terminal on linux mint 17. it showing curl: Remote file name has no length! attached screen shot.
![error](https://cloud.githubusercontent.com/assets/5629946/9116494/37d1a46a-3c97-11e5-9fa6-b2fdffbf413b.png)

**Comment by Deborah-Digges** [comment]
The command you used seems to be incorrect.
Copy the following: 

~~~
 curl -0 http://openhatch.org/missions/diffpatch/diffsingle/nutty-pancake.txt -o original.txt
~~~

Note it's

curl *-0(zero)*  [url of remote file] *-o(small O)* output-file.

The *zero* tells curl to use http1.0
and the small oh is used to save the file to an output file.

**Comment by ehashman** [comment]
Thanks for your excellent response here, @Deborah-Digges :D

**Comment by slrslr** [comment]
I think that this error can have also the cause where curl gets unknown switch. For example you use -retry instead of --retry.
