### ISSUE TITLE
curl: Remote file name has no length!

### ISSUE THREAD

**Issue by IntuitiveLeap** [openhatch/oh-mainline#1694]
OS: win7 ult 64 bit
Browser: Chrome Version 45.0.2454.85 m
Command Prompt being used: Git-Bash

On the Mission page:
https://openhatch.org/missions/diffpatch/single_diff
the instructions ask the user to use the following commands (copied directly from the webpage)

curl -O https://openhatch.org/missions/diffpatch/diffsingle/nutty-pancake.txt
curl -O https://openhatch.org/missions/diffpatch/diffsingle/nutty-pancake.txt -O original

These instructions do not provide useful commands as far as I understand curl. the upper case 'O's are not being used correctly and probably should be  '0' (the zero character) in certain locations. Using the existing instructions will generate the warning message seen as the title of this issue and cause the user to only download the first file.
![capture](https://cloud.githubusercontent.com/assets/767235/9722001/5e1bd344-5573-11e5-80ed-d0d1c9a6cd87.JPG)

**Comment by ehashman** [comment]
Related to #1685. Looks like we need an update to the documentation.

**Comment by nirmeshkhandelwal** [comment]
Hi. I would like to work on this. I am a new user trying to make my first contribution in open source. Please let me know how should I proceed with this.

**Comment by Deborah-Digges** [comment]
Hi @nirmeshkhandelwal . I have opened a PR for this:https://github.com/openhatch/oh-mainline/pull/1695. Do have a look

**Comment by ehashman** [comment]
@nirmeshkhandelwal, looks like @Deborah-Digges got to it before you. I am going to call this resolved.

However, as a follow-up, would it be possible to update the documentation that uses wget to use curl instead? I've seen this request a number of times now (see suggestion on #1316 but I think I've also seen it elsewhere). #1316 is specific to the tar mission but perhaps a PR could be more expansive.
