### ISSUE TITLE
Broken pages from Heroku migration

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1701]
Paging @jwm! We had a report that the wiki was down, and I'm assuming this is related to the site migration. Here's a list of pages I've found 404-ing:

https://openhatch.org/wiki (including https://openhatch.org/wiki/Privacy_policy)
https://openhatch.org/blog
https://openhatch.org/about
https://openhatch.org/contact

That's all for now but there might be more! Wiki and blog are probably pretty critical, so I've marked this issue as such.

**Comment by willingc** [comment]
@ehashman Yep. @jwm did a great job on the migration and left a message in the PR (I think) re: the wiki and the links.

**Comment by jwm** [comment]
I can look more at the wiki and blog links, but probably not until tonight or tomorrow night. In the meantime, it would really help if @paulproteus could chime in on #1590, since it's difficult to make heads or tails of what the nginx+Apache configuration is doing on linode.openhatch.org.

**Comment by jwm** [comment]
I got the wiki and blog proxying working again. It used to be that the web server (nginx and/or Apache) did this proxying for /wiki and /blog, so I implemented the same functionality in the Django app to fix this.
