### ISSUE TITLE
Link on home page for bug tracker needs update

### ISSUE THREAD

**Issue by willingc** [openhatch/oh-mainline#1702]
The link on OpenHatch's home page for "Bug Tracker" is giving a 404 error. The correct link should link to the oh-mainline GitHub Issues https://github.com/openhatch/oh-mainline/issues

Message re: post migration issues #1590

**Comment by willingc** [comment]
This issue is suitable for a new contributor. The link would be edited in https://github.com/openhatch/oh-mainline/blob/master/mysite/base/templates/base/base.html file.

**Comment by jwm** [comment]
Was in the process of working on this anyway, since I was deciphering the linode.openhatch.org Apache and nginx configurations. :-)

**Comment by willingc** [comment]
@jwm Thanks for the fix. :penguin:
