### ISSUE TITLE
The problem in creating the database 

### ISSUE THREAD

**Issue by maheshbabu2804** [openhatch/oh-mainline#1734]
The project has been cloned and wanted to build it . The command of "python manage.py syncdb --migrate --noinput" is used and the output of warnings or errors are displayed .

Here is the output of the command : 
Migrating...
UnknownMigration: Migration 'httpproxy:0001_initial' probably doesn't exist.
Traceback (most recent call last):
 > File "/home/mahesh2804/openhatch/oh-mainline/vendor/packages/south/south/migration/base.py", line 310, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
>  File "/home/mahesh2804/openhatch/oh-mainline/vendor/packages/django-http-proxy/httpproxy/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations

**Comment by djrollins** [comment]
I have also run into this issue. It happens consistently on both OSX Yosemite and Fedora 22.

I rolled back to commit 1814967584c8a50b58e79590eeb8eb463baff693 which is the parent of the commit where a lot of the django-http changes were made (51ca2717247cffbf418a26f332b54dbcd82ec462) and I was able to migrate the database just fine.

So I can only assume that a bug has crept in with that rather large commit. Unfortunately, I haven't any experience with Django so I cannot offer any more insight. But if you checkout the linked commit, migrate the db, then checkout master again you should be able start running the db locally.

**Comment by ehashman** [comment]
Hi @djrollins, thanks for looking into that. Would it be possible for you to do a git-bisect to determine the exact commit that broke the migrations? Then I can look into fixing this. Here's some documentation on git-bisect: https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search

Alternatively, I can possibly look into it if you don't want to.

**Comment by djrollins** [comment]
Hey @ehashman, sorry for the delayed reply. I can take a look into this over the next few days.

**Comment by djrollins** [comment]
I ran a git-bisect and can confirm the commit that introduced the bug was 51ca2717247cffbf418a26f332b54dbcd82ec462.

I'll take a look and see if I can reason about what may be going wrong.

**Comment by ehashman** [comment]
Fantastic! And @djrollins this makes total sense; there were some migrations introduced in that patch in the vendor directory and match @maheshbabu2804's error message above.

So now I think this is in @jwm's ballpark. He added the vendor packages that caused the breakage. I'm surprised this didn't affect production! Any comments?

I'm also going to bump up the urgency of this bug since it is preventing new contributors from getting started.

---

Hacky and terrible workaround in the interim for you, @maheshbabu2804, is to first 

```
git checkout 51ca271^
```

and *then* perform the migrations. Then you can checkout `HEAD` again, and your database will probably work. Or you could also wait on a fix---up to you :)

**Comment by jwm** [comment]
Production database migrations worked fine, even when I accidentally ran them on a local sqlite database, so I'm not sure what's going on here. I don't think I'll have much time for this in the next couple of weeks, so I'm more than happy if someone wants to tackle this.

One option might be removing the httpproxy module, but that would break the proxying for the Wiki (i.e., openhatch.org/wiki/ would no longer transparently present the wiki at wiki.openhatch.org). If we don't mind making that a redirect instead, we could redirect openhatch.org/wiki/* to wiki.openhatch.org/*.

The other option is looking into the httpproxy module, which is an off-the-shelf Django module I found to do HTTP proxying. Maybe there's an alternative, or a newer version, or an existing issue on that module that we could +1.
