### ISSUE TITLE
git training mission, creating a patch, 500 error

### ISSUE THREAD

**Issue by mstrout** [openhatch/oh-mainline#1737]
We get an Error 500 (server error) when we are on the "Creating a Patch" page after submitting the output from creating a patch.  All four of us got the same error.  We are using the following web browsers: Edge in Windows 10, Chrome in Windows 7, and Safari for Mac OS X 10.10.5.
We are at OpenSource Day at GHC.  Tiffany Brooks, Rieko Tsuji, Elsa Gonzalez-Aguilar, and Michelle Strout.

**Comment by tbrooks530** [comment]
Thank you for the shout out!

**Comment by rodgzilla** [comment]
I experience the same problem.

I am using chrome Version 42.0.2311.152 (64-bit) on Ubuntu 14.04.

**Comment by ehashman** [comment]
This may be related to the recent Heroku migration. I don't think I have access to investigate. @jwm?

**Comment by Naruto0** [comment]
Firefox 40.0.3, Xubuntu 14.04, trying to reach https://openhatch.org/missions/git/diff/submit#gitdiff-form, same with me, 500 internal server error.

**Comment by jwm** [comment]
Yup, this is a known bug post-Heroku. The commands in https://github.com/openhatch/oh-mainline/blob/master/mysite/missions/git/view_helpers.py#L72 need to execute on linode.openhatch.org using the REMOTE_REPO_ACCESS_SPEC, like the others in that file.

**Comment by pdurbin** [comment]
@jwm how easy is it to test a fix from a developer's laptop? Is there some way to mock `if settings.REMOTE_REPO_SETUP_ACCESS_SPEC`? Apologies if this is a stupid question. I guess another way to ask this is if there's a way to write a failing test for this bug. /cc @paulproteus @ehashman @willingc

**Comment by jwm** [comment]
@pdurbin sorry it's been a while, we've been shipping something big at work and it's been taking up a lot of time, and I'm going to be traveling for the next week or so.

I'm happy to have someone else tackle this - if that person is you, you'll need to update the `commit_if_ok()` method I linked to earlier to execute its commands remotely - see what the `exists()` method does in that file for example. You'll also need to add a small management command (see https://github.com/openhatch/oh-mainline/blob/master/mysite/missions/management/commands/git_exists.py for an example) that exposes `commit_if_ok()` to remote commands.

**Comment by jwm** [comment]
The `format-patch` phase of this mission should be all set now.

**Comment by Naruto0** [comment]
Thanks John.
