### ISSUE TITLE
Profiles pictures of people do not appear

### ISSUE THREAD

**Issue by SanketDG** [openhatch/oh-mainline#1746]
In https://openhatch.org/, none of the profile pictures seem to appear in the "Recent site activity"

Screenshot:
![image](https://cloud.githubusercontent.com/assets/8980971/10757077/5eb6b5bc-7cce-11e5-949a-e140c02ab0db.png)

It also does not appear on the profile page, for example, https://openhatch.org/people/lukasz/

<hr>

Also, I see the css files in this project are are written in less.
I have a question about how are they compiled, or how do I see the changes in the local server after I have made some edits to those less files? I am unsure of the procedure involved.

**Comment by ehashman** [comment]
Hey @SanketDG,

I totally agree! I noticed this bug myself, and I suspect it is database-migration related. 

There has been some discussion about removing the people/projects/profiles section of the site, so I don't know how high-priority this is.

In regards to the less issue, please file a separate issue :)

**Comment by trishnaguha** [comment]
@SanketDG This might be helpful to run the local instance http://openhatch.readthedocs.org/en/latest/getting_started/installation.html :)

**Comment by SanketDG** [comment]
@trishnaguha Thanks!
