### ISSUE TITLE
Bug: `ls --help` doesn't work in all bash shells

### ISSUE THREAD

**Issue by li3n3** [openhatch/oh-mainline#1752]
https://openhatch.org/missions/shell/ls states “There are many other options available. For more options, type ls --help in your shell and you'll get a list of available options along with a short description for each option. (if you are on zsh type man ls)”.

I’m using bash on OS X, and while `ls --help` doesn’t work, `man ls` works just fine.

**Comment by ehashman** [comment]
Does `man ls` work on the Windows git bash shell (or cygwin shell)? I guess that would be my compatibility concern.

**Comment by trishnaguha** [comment]
```man ls``` works on cygwin shell. So Should I change ``` ls --help``` to ```man ls``` and change the description there? Or Should I just add "OS X bash' with "zsh type" ?
