### ISSUE TITLE
Typos/clarity suggestions for training missions!

### ISSUE THREAD

**Issue by li3n3** [openhatch/oh-mainline#1754]
* [x] At the bottom of https://openhatch.org/missions/shell/file-and-directory, “Visit here to know about what are paths and what is the difference between absolute and relative paths” could be a little clearer. Maybe “Click here to learn about paths and the difference between absolute and relative paths.”
* [x] https://openhatch.org/missions/shell/ls “owner of the file and it's permission” => “owner of the file and its permissions” (it’s/its, and there’s more than one permission)
* [x] Point 3 on that page could be tightened up a bit: “ls command with option -a i.e. ls -a will list all the files including hidden files starting with '.' (hidden file's name starts with '.')” => maybe “ls command with option -a (i.e. ls -a) will list all files, including hidden files (whose names start with ‘.’)”
* [x] On https://openhatch.org/missions/shell/create-and-remove, there’s a line that says “mkdir will return a warning message such as mkdir: cannot create directory 'dir1': File exists and will not create a file with that name.” but it doesn’t really explain what could cause that. Not too hard to figure out, but adding e.g. “If a directory with that name already exists in the current directory, “ beforehand would make it a little clearer.
* [x] “For example, to remove test.txt present in your current directory, you will have to type” is a little strong; could be “For example, to remove a file named test.txt in your current directory, you can type” instead.
* [x] The “Removing directories” section includes important information; it just reads a bit bumpy. (The description of recursive deletion might benefit from a fresh pass, too — recursion can be a trip at the best of times! Would love to talk about this.) This could be a cool place to introduce rmdir, but teaching about -r is pretty aces.
* [x] “Remember? earlier we explained how recursive option worked ?” paragraph could use just a little cleanup. (If the above “recursively” description does change on the other page, it should change here, too.)
* [x] On https://openhatch.org/missions/shell/more-info: “We introduced you with few of” => “We introduced you to a few of”.
* ~~"Let's go the list of missions" appears after completing tarball mission successfully; just needs another word in there!~~ can't find this anymore, so I'm guessing someone else got to it? yay!
* [x] The first line of https://openhatch.org/missions/diffpatch/hints is a bit confusing: “When working with patch, you are dealing with a patchfile containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions.”
* [x] On the same page, does “window” in “For window users” refer to Windows, or something else?

Let me know if I should split these out at all — it seemed like they were all on the same theme, and I would looooove to go through and edit any/all of this.  :)

**Comment by ehashman** [comment]
Hi @li3n3!

While I don't have time to respond directly to all these issues right now, I just wanted to personally thank you for all the great issues you've filed against this repository. I am going through and triaging them now. Also, if you like, feel free to submit a pull request for any of them. If you need help, me and a number of others are available on IRC.

Welcome!

**Comment by li3n3** [comment]
Thank you for your help!

Definitely would like to PR this stuff — I'll see you in IRC whether or not I get stuck there.  :)
