### ISSUE TITLE
Update formatting on the bugsets error message "(Could not reach server when refreshing page data.)"

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1763]
This text is gigantic and pops up any time a connection refresh fails (yet still better than the previous popup I used!). I think that we should

- [x] Only show this message after a lot of attempts fail. Currently if a single requests fails, it will pop up, but the next one 5 seconds later succeeding will clear the message. This is not a very good UX.
- [x] Update the CSS to shrink the message size. (this is the **bitesize** part of this issue) It currently looks like this:

![](https://cloud.githubusercontent.com/assets/3866405/4543083/0a605bb0-4e28-11e4-8527-5cd62932a7ad.png)

Related issue: #1424

**Comment by Deborah-Digges** [comment]
This looks good @gnarula. Thank you for you contribution!
<img width="1242" alt="screen shot 2015-10-31 at 6 15 33 pm" src="https://cloud.githubusercontent.com/assets/3866405/10863663/93c9f82e-7ffb-11e5-8b35-cba57a52a39d.png">

I've tested it and it works just fine :+1: 
Please could you send us a mail to permit us to use your work if you haven't done so already: https://openhatch.readthedocs.org/en/latest/getting_started/handling_contributions.html#permit-us-to-share-your-work

**Comment by gnarula** [comment]
@Deborah-Digges sure thing. Done :)

**Comment by ehashman** [comment]
Thank you for your work on this fix, @gnarula and @Deborah-Digges!
