### ISSUE TITLE
Add link to bugsets to the main openhatch page

### ISSUE THREAD

**Issue by ehashman** [openhatch/oh-mainline#1764]
Currently, http://openhatch.org/bugsets isn't linked anywhere on the site. This is a bit of a shame, because people won't be able to find it and use it.

Pending the fixes in #1762 and #1763, it would be cool to add a link to the main OpenHatch page so people can find this tool.

**Comment by vipul-sharma20** [comment]
Hello @ehashman. Where exactly should we add the link to the bug set organizer? in the home page or in the project page : `openhatch.org/search/` ? how about under the option from where we add new projects in /search/ page ?

**Comment by ehashman** [comment]
I was thinking on the homepage somewhere, so people can actually find it. But I'm not exactly sure how that should look. It's definitely not related to projects (although it looks a bit similar to `/search`) so I wouldn't hide it there :)
