### ISSUE TITLE
Unable to run Openhatch locally. Getting 'Cannot import Migrations' error.

### ISSUE THREAD

**Issue by waseem18** [openhatch/oh-mainline#1768]
I'm unable to run OH locally. I tried to run it on a couple of PC's which ran OH locally earlier but I'm unable to run it now.  

![prb](https://cloud.githubusercontent.com/assets/5843007/10888759/05de688c-81b4-11e5-967a-467cea7399f1.PNG)

I tried to install and update Django as well as South but in vain.

**Comment by Deborah-Digges** [comment]
Please refer to this thread:https://github.com/openhatch/oh-mainline/issues/1734

**Comment by waseem18** [comment]
Thanks @Deborah-Digges for referring that thread.

Running the command : git checkout 51ca271^ before syncing the db resolved the issue. :+1:

**Comment by Deborah-Digges** [comment]
No problem :penguin: Do reach out  if you have any other questions

**Comment by SanketDG** [comment]
@ehashman This can be closed too. Fixed by #1773

**Comment by ehashman** [comment]
Both issues closed, this one as a duplicate and the other automatically by the PR, thanks @SanketDG !
