### ISSUE TITLE
Devel mailing list

### ISSUE THREAD

**Issue by t-darxt** [openhatch/oh-mainline#1782]
lists.openhatch.org/mailman/listinfo/devel page not loading. I see nothing. I'm clicking the link on http://openhatch.readthedocs.org/en/latest/getting_started/getting_started.html, opening a new tab, but nothing in new tab.

**Comment by doug-wade** [comment]
I just subscribed to the devel mailing list at http://lists.openhatch.org/mailman/listinfo/devel, so it may have been a transient error.  Would you mind trying again?  And if you encounter the same problem again, can you include any error messages you get?  Knowing if you're getting a 404 vs a 500, for instance, would help a lot in debugging your issue.

**Comment by t-darxt** [comment]
I tried again and subscribed. It is okay now :+1:

**Comment by SanketDG** [comment]
@t-darxt Then I am guessing you can close this issue.
