### ISSUE TITLE
About link on main page is not working

### ISSUE THREAD

**Issue by GuidoS** [openhatch/oh-mainline#1789]
Not sure why, but the about page is down. I get a "Error 500 (server error)".

**Comment by waseem18** [comment]
It's not only with the 'About' page. Most of the links (90%) give Error 500.

**Comment by ehashman** [comment]
Hi all,

The site is not under active development or maintenance currently. Someone with Heroku access would have to look into it, but I suspect this is not a high priority right now. Sorry :(

**Comment by GuidoS** [comment]
Wouldn't it make sense to leave up a splash screen to this effect if the site is not currenlty working. I would hate to leave the impression that this community is falling apart.

**Comment by ehashman** [comment]
@GuidoS I suggest that you make this suggestion on the devel@lists.openhatch.org mailing list?

**Comment by GuidoS** [comment]
I am closing this issue.
