### ISSUE TITLE
500 in contact link

### ISSUE THREAD

**Issue by gautamkrishnar** [openhatch/oh-mainline#1791]
https://openhatch.org/wiki/Contact

**Comment by divayprakash** [comment]
not just the contact link, even [https://openhatch.org/wiki](https://openhatch.org/wiki) is broken

**Comment by ehashman** [comment]
Re: the wiki, it has moved to a subdomain: http://wiki.openhatch.org/Main_Page

Not sure why the redirect isn't working, pinging @paulproteus

**Comment by harikishen** [comment]
https://github.com/openhatch/oh-mainline/pull/1794

**Comment by JohnMHarrisJr** [comment]
The Contact link is still 500'ing

**Comment by gautamkrishnar** [comment]
I think this one is fixed... Closing the issue...
