### ISSUE TITLE
Provide an API that is a post-commit hook that tells us to refresh our index of a repository

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#323]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Rich Jones suggests this. I think it's ingenious.

&gt; What about
&gt; other independent repos.. will there be an API, so I can integrate with
&gt; a git hook?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/voltagex/'>voltagex</a>:</b><dl><dd>This would solve the issue of having to manually refresh the indexes to stay up
to date with external repositories.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/voltagex/'>voltagex</a>:</b><dl><dd>See also #39.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I'm not currently working on this. Someone else can grab it!
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  paulproteus, voltagex </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>8</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue8'>view archived page</a>)
Last modified: <b>2011-03-19.20:59:23</b>

**Comment by willingc** [comment]
Recommend closing since the GitHub API has evolved quite a bit since this issue.
