### ISSUE TITLE
"Project Graveyard" function

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#353]
<b>Comment by <a href='https://openhatch.org/people/voltagex/'>voltagex</a>:</b><dl><dd>Occasionally I come across a really interesting project that has unfortunately
been abandoned (source-control hasn't been updated for a while, website no
longer exists etc etc)

It might be a good feature to be able to have these projects listed as "Projects
free to a good home" or something like that, to try and kickstart these again.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>That's a cool idea. There is already the <a href="http://www.unmaintained-free-">http://www.unmaintained-free-</a>
software.org/wiki/Main_Page project -- but we could send people there, or import 
data from them.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/voltagex/'>voltagex</a>:</b><dl><dd>I'm in favour of the import/aggregate route instead of linking people away to
other sites. Maybe I'm a control freak, but a little of the Cathedral in the
Bazaar won't hurt.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>This bug is being tracked in <a href="https://openhatch.org/bugs/issue246">https://openhatch.org/bugs/issue246</a>
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  palhmbs, voltagex </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>38</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue38'>view archived page</a>)
Last modified: <b>2011-07-02.20:38:28</b>

**Comment by sparrowunderscore** [comment]
It looks like http://www.unmaintained-free-software.org/ has ceased to meaningfully exist. :(

**Comment by ehashman** [comment]
@paulproteus and I think this is probably out of scope for OpenHatch right now, so I've closed the issue and marked it as a wish. If someone is specifically interested in taking this on, that could be cool, though.
