### ISSUE TITLE
import project descriptions when importing from Ohloh

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#379]
<b>Comment by <a href='https://openhatch.org/people/keturn/'>keturn</a>:</b><dl><dd>When openhatch imports a project, I don't want to have to manually describe it 
again if that information is available somewhere else.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>That's a good idea, where by "good" I mean "seriously duh good".

We already do that for Github imports, but not for Ohloh imports, I believe. 
We'll get on that.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/Mark/'>Mark</a>:</b><dl><dd>I'll take this one.  It looks like the Ohloh API provides a description tag.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Oh my God, you rock.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/Mark/'>Mark</a>:</b><dl><dd>Taking myself off being the assigned person, for the next two weeks. If someone
else can look at it sooner, great. I won't be able to do much over the next few
days as I prepare to leave for a couple of weeks.  

I've looked at this briefly, but nothing I've done seems to get the actual call
to ohloh.get_contribution_info_by_ohloh_username to pick up the description.
Trying to pick up project_data['description'] gives a key error and picking up
c_f.get('description', '') gives the defaulted empty string, even on projects
with a description.  I also noticed some of the customs test were failing after
the most recent pull. No idea if that is a python 2.6 issue (local to my
machine) or something else.

I'll dig into it deeper when I get back from vacation, of no one else has
handled it.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  Mark, keturn, paulproteus, rafpaf </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>64</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue64'>view archived page</a>)
Last modified: <b>2010-05-16.21:44:52</b>

**Comment by paulproteus** [comment]
Since we don't do any kind of profile importing anymore, we won't be able to implement this feature.

If we do re-add a profile importer, we can come back to this.
