### ISSUE TITLE
wildcard e-mail addresses

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#380]
<b>Comment by <a href='https://openhatch.org/people/bill_mcgonigle/'>bill_mcgonigle</a>:</b><dl><dd>I always sign up for bugtracker accounts taking advantage of address expansion.  Here I'd use bill-
<a href="mailto:openhatch.org@bfccomputing.com.">openhatch.org@bfccomputing.com.</a>  gmail foks might use <a href="mailto:bill+openhatch@gmail.com">bill+openhatch@gmail.com</a>, or some such.  So, in 
OpenHatch, I'd need to create something like bill*@bfccomputing.com or even bill.*@bfccomputing.com to 
get really geeky for it to find my various contributions.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>That's an interesting idea. I can see if it's going to be compatible with the
way we search Ohloh.net's code index for your contributions.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Here's something that would be possible:

1. Bill enters "*@bfccomputing.com" into the importer

2. We search Ohloh's repository index for bfccomputing.com

3. We filter the results so that they must match the expression he entered

That seems feasible... to explain it, we'd have to add a link to a "What
can/should I enter into this form?" page. That might be generally useful to set
people's expectations properly.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/bill_mcgonigle/'>bill_mcgonigle</a>:</b><dl><dd>Keep in mind, if you only wildcard the domain, you'll have trouble with, e.g.
gmail or any site with multiple users.
The way some big universities use the nomenclature is <a href="mailto:user+@example.com">user+@example.com</a> where
anything after + is ignored for the purposes of plus expansion.
With the advent of bad web forms which choke on '+' (as a lazy %20), lots of
folks also support other characters.  I thought perhaps '*' might be a
reasonably evident way to indicate expansion in general, but I see now that's
also a valid e-mail character.  Only ()&lt;&gt;@,;:\" are dis-allowed from the
local-part per RFC.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  bill_mcgonigle, paulproteus, rafpaf, stump </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>65</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue65'>view archived page</a>)
Last modified: <b>2010-05-27.12:49:04</b>

**Comment by paulproteus** [comment]
This isn't relevant anymore, as there is no profile importer.
