### ISSUE TITLE
Project Icons are not always extracted correctly from Ohloh

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#510]
<b>Comment by <a href='https://openhatch.org/people/fhaag/'>fhaag</a>:</b><dl><dd>When automatically searching for contributions by a given author name on Ohloh,
project icons are used only sometimes.

cf. this contributor: <a href="http://openhatch.org/people/fhaag/">http://openhatch.org/people/fhaag/</a>
Wallpaper Website Tool and Flexible Localization have the correct icons, The
Two-Layered GUI Toolkit and Toolbar Icons do not. All four were extracted at the
same time from Ohloh; same contributor name (fhaag), same repository type (SVN),
same code hoster (SourceForge).
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/fhaag/'>fhaag</a>:</b><dl><dd>corrected the title
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>The issue here is that I haven't been able to reliably get project icons from Ohloh.

If someone wants to help fix this, I would be willing to show how we use the
Ohloh API and why we're having troubles.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  fhaag, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>195</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue195'>view archived page</a>)
Last modified: <b>2011-07-02.20:29:03</b>

**Comment by paulproteus** [comment]
We do still get project icons from Ohloh. And they're still not always right.

...then again, does this feature actually work? If we deleted it, would anyone notice? Hmm.

**Comment by paulproteus** [comment]
I just confirmed that the feature does not work. I'll file a new issue for deleting the code.
