### ISSUE TITLE
AJAXify image upload

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#560]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>When people upload personal profile images, or project icons, if we used AJAX,
we could give them immediate feedback as they do the upload.

That seems like it would be super nice.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>245</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue245'>view archived page</a>)
Last modified: <b>2011-01-29.23:28:04</b>

**Comment by vipul-sharma20** [comment]
@paulproteus, do you mean like an image upload progress bar ? this would be nice as, if I try to upload a large size image (something around 2MB), the page seems to be stuck but actually it is uploading so it would be a nice addition.

**Comment by paulproteus** [comment]
Yeah! A progress bar is a great example of how it might work.

**Comment by ehashman** [comment]
Closed by #1540.
