### ISSUE TITLE
sufjan can't log into MediaWiki

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#632]
<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>Since the central login system was implemented, sufjan has been unable to log
into MediaWiki. This is sad, and causes the MeetBot plugin to fail.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>Bumping.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>Hmm, this seems at face value unrelated to the central login system - the site
login works fine (now that I have enabled password login for sufjan) but the
actual API edit call returns:

APIError(u'badtoken', u'Invalid token', None)

It is possible that something in the API is being unintentionally affected by
the AuthDjango plugin. I'll have to dig deeper...
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>Bumping (again).
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>Deassigning myself due to lack of time. Anyone is free to grab it; if they need
to patch the AuthDjango plugin then do so and I'll happily commit patches to the
repo once reviewed.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Good news and bad news.

The good news is, we diagnosed the 'badtoken' problem. In fact, it's fixed
through a hack to AuthDjango, as discussed on OH-Dev!

The bad news is I have no idea what is going wrong now because I can't quite
understand MeetBot's configuration.

I'm bumping the priority of this down for now.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I've got my plate full for the next couple of weeks, but after that I
can probably pop in and have a fiddle.

Cheers
Jack

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Mozilla - <a href="http://enigmail.mozdev.org/">http://enigmail.mozdev.org/</a>

iQEcBAEBAgAGBQJP5SV+AAoJEI3j92WSe+b31E8H/3UcGd15xxG+NWwVQYPghDhp
hnpFBQ2imD0FpzA6itBTPuSOh/Gz7MgUVxMF7O88ocCHDx5RxkuepSBIVkyz31iH
jTmh08+m1azk5/bYk538AZrUixFiulrr/fioF783TcfKqJR/J1FXUe7GAfMQqsFv
Fpz8EqYy12BbsMAQ/omeaFDAWxE7V2Cjdqo/PbHb8DPWJrAqlOHKpJoIM0w2Z+HD
otoBCHSyXLuD7PjHnA1eXiOMQC8lwJCkXfCcqIyaHFm6Lao3oYMQkcuzjWnuN24m
j1B6hZCXLIja/WENUz3j10vJM4R5VJnWiTq+6blwrVifPMoROwBl3o5Rgw41M+8=
=i6WJ
-----END PGP SIGNATURE-----
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Yay! (Also maybe that would be a good time to document it some more.)
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  paulproteus, pythonian4000 </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>317</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue317'>view archived page</a>)
Last modified: <b>2012-06-24.01:25:38</b>

**Comment by paulproteus** [comment]
We no longer have the sufjan bot in the #openhatch IRC channel, so I will close this.

If we need MediaWiki functionality again with a bot, then we can look into it then.

Thanks to @ehashman for bringing this to my attention and to @pythonian4000 for years of useful service of of the sufjan meeting bot!
