### ISSUE TITLE
Project importer UI is confusing

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#704]
<b>Comment by <a href='https://openhatch.org/people/akkana/'>akkana</a>:</b><dl><dd>In the "Start here" project importer, the first two text fields specifically ask
for a username and an email address. Once you've filled those out, a new text
field appears with no indication what it's for ... except that it's across from
"Suggest a data source" so I ended up typing "ohloh" in that field, thinking I
would be filling out one of these for each possible data source.

It might be clearer if the description said something like "We'll search for all
these names and email addresses to find projects where you've been active."

Paradoxically, it also might be clearer if the first two didn't specifically ask
for a name and an email address -- that made it seem like I needed exactly one
of each, so when the third field appeared it must be for something else.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>This is definitely a bug rather than a wish - if a user has trouble with
understanding or using the UI then by definition it's a problem ^_^
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  akkana, paulproteus, pythonian4000 </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>389</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue389'>view archived page</a>)
Last modified: <b>2011-07-02.20:28:56</b>

**Comment by paulproteus** [comment]
We no longer have a profile importer, so I'm closing this. It's convenient that removing code means we don't have to fix user experience problems.

Regardless, thanks @akkana for filing it!
