### ISSUE TITLE
Logged-in home page contents only appear as one column (under some set of circumstances)

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#731]
<b>Comment by <a href='https://openhatch.org/people/aldeka/'>aldeka</a>:</b><dl><dd>See screenshot, of Chromium on my Ubuntu-running laptop.

Tried shrinking and expanding the page within my browser, but that didn't change 
the relative dimensions / fix the floats.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jessica/'>jessica</a>:</b><dl><dd>Oh weird! I'm sorry that's happening to you. I just tried on mine with the version 
in production and I still have 2 columns.  

I tried on Ubuntu 10.10: Chromium 10.0.648.205, Firefox 3.6.17; Win7: Chrome, 
Firefox, and IE8.  

May I see the second half of your screen? My theory is that it's a person. I can 
hide the overflow or tweak the person lister module thing that is used. Might be a 
weird clash happening.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>I suggest using div's to divide up what you want in each "column"
(float:left; - float: right;) or use an old-fashioned table?
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file260/Screenshot-OpenHatch%20-%20Home%20-%20Chromium.png by aldeka</b>

Status: <b>chatting</b>
Nosy List: <b>  aldeka, palhmbs, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>416</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue416'>view archived page</a>)
Last modified: <b>2011-07-02.20:23:53</b>

**Comment by ehashman** [comment]
When @paulproteus checked out that the PNG rendered properly in his browser, he might have also suggested that this bug is no longer relevant given that the home page has been redesigned muchly since this was filed ;) Closing.

**Comment by paulproteus** [comment]
+1
