### ISSUE TITLE
When you log in with a password (not OpenID) then we lose the ?next parameter

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#819]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I just watched a user:

* Hit the main page of OpenHatch
* Go to the training missions
* Get to the point in the 'tar' mission where you have to sign up
* Sign up with a password
* Discover that he is not where he expected to be

I think this is because ?next= got lost.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>504</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue504'>view archived page</a>)
Last modified: <b>2011-07-25.12:19:29</b>

**Comment by su7edja** [comment]
Pull request for this issue https://github.com/openhatch/oh-mainline/pull/1587

**Comment by paulproteus** [comment]
Marking as resolved. Huge thanks to @su7edja .
