### ISSUE TITLE
Create generic "OpenHatch Comes to Campus" event flier that people can reuse

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#898]
<b>Comment by <a href='https://openhatch.org/people/aldeka/'>aldeka</a>:</b><dl><dd>Formats: PSD, XCF, SVG?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/aldeka/'>aldeka</a>:</b><dl><dd>Also see <a href="issue536">issue536</a> -- could also use a more generic OH poster design.
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  aldeka, paulproteus </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>583</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue583'>view archived page</a>)
Last modified: <b>2012-02-08.23:21:10</b>

**Comment by dcwalk** [comment]
Moved to openhatch/open-source-comes-to-campus#113 as this is for OSCTC publicity.
