### ISSUE TITLE
Refactor our training missions' backend so that they use class-based views

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#960]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Right now, the various views in mysite/missions/*/*.py use a combination of a
few programming paradigms.

There is a class called MissionPageState that tracks the progress of a user
through the steps of a particular mission (e.g. the svn mission).

The GET or POST requests for a page call functions which generally look very
close to the same.

I think we can increase clarity and decrease lines of code by turning the
missions' views.py files into classes that use inheritance to move logic into
unified places. 

We can be inspired by the very simple TemplateView provided by Django, and as
used in the Windows informational tutorial at mysite/missions/setup/views.py .
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>(Note that we don't have to use Django's generic views system. We can instead
use our own classes.)
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I'll take this. I think that doing this refactoring is a really good idea before
I write up documentation on how to add missions.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>This is in progress -- the Subversion mission has the latest version of this.

It needs a bit more work, and I think we should finish this shortly. Marking as
"later" for now because it's not ready for 0.11.12.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I'm going to bump this out of 0.12.02 into the future. Hopefully we'll get to it 
during this weekend's sprint!
   
</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>feature</b>
Waiting On: <b>#Missions: Switch subversion mission to purely use class-based views</b>
Imported from roundup ID: <b>645</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue645'>view archived page</a>)
Last modified: <b>2012-05-09.21:44:28</b>

**Comment by willingc** [comment]
Closing. See #1709 re: svn mission.
