### ISSUE TITLE
Prefil Google Code tracker fields

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#988]
<b>Comment by <a href='https://openhatch.org/people/techtonik/'>techtonik</a>:</b><dl><dd>Some ideas about improving user experience when adding Google Code tracker.
1. Use Google name as Tracker name by default
2. Use Component-Docs as documentation label by default as it is the default
3. Drop-down for available parser classes?
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  florapdx, paulproteus, techtonik </b>
Priority: <b>feature</b>
Imported from roundup ID: <b>673</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue673'>view archived page</a>)
Last modified: <b>2013-08-03.02:07:17</b>

**Comment by ehashman** [comment]
Since [Google Code is being shut down entirely](http://arstechnica.com/information-technology/2015/03/google-to-close-google-code-open-source-project-hosting/), I'm going to close this as out of scope.

**Comment by paulproteus** [comment]
Oh man, that is sad and amazing and I forgot about that.​
